### ISSUE TITLE
Move site over

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda-docs#1]
@tomkerkhove I hooked up Netlify to this repo, and pointed [https://keda.sh](https://keda.sh) to it.  You should be  able to stick your code here.  In our contributor guide we’ll just enforce people need to open a PR on this repo if there are doc impacting features before they’ll get approved

**Comment by tomkerkhove** [comment]
Is there a reason that it's a seperate repo? I was planning on pushing to the current one with folder /docs actually so that everything is in one PR.

Otherwise docs will very unlikely be added I think

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by tomkerkhove** [comment]
See discussion on https://github.com/kedacore/keda/pull/433

**Comment by jeffhollan** [comment]
@tomkerkhove let me know if you want me to grab af we of the scalers or other sections and I can help add docs for them
