### ISSUE TITLE
Incorrect CPU Scaler documentation

### ISSUE THREAD

**Issue by hajdukda** [kedacore/keda-docs#1028]
# Which page requires fixing ?

https://keda.sh/docs/2.9/scalers/cpu/#prerequisites

# Why this page requires fixing ?

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#how-does-a-horizontalpodautoscaler-work

> the controller calculates the utilization value as a percentage of the equivalent [resource request](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits) on the containers in each Pod

Limits don't take part in HPA autoscaling. Limits are used just to limit the number of resources specific container can use.
That's why we can set for example 200% CPU utilization for target of HPA..

**Comment by zroubalik** [comment]
Good catch, would you mind opening a PR with a fix? Thanks!

**Comment by mootpt** [comment]
opened #1095 to address.
