### ISSUE TITLE
Provide guidance how to build an external scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#104]
Our current [external scaler](https://keda.sh/scalers/external/) docs are very basic, we should enrich them in what it requires to be an external scaler.

Things it should cover are:
- What does it need to expose
- What are the data contracts that are required
- ..

Providing an OpenAPI spec for this might be a good option?

**Comment by tomkerkhove** [comment]
@ahmelsayed @TsuyoshiUshio can you give some insights on this?

**Comment by tomkerkhove** [comment]
@ahmelsayed @zroubalik Can you guys help with this? What does it take to be a good external scaler?

If we have that, I can provide an OpenAPI spec to comply with.

**Comment by tomkerkhove** [comment]
Apparently protobuf schema is the way to go for gRPC, added issue on https://github.com/kedacore/external-scalers/issues/3 to provide one

**Comment by tomkerkhove** [comment]
@ahmelsayed Can you pick this up given we have a lot of questions about this?

**Comment by ahmelsayed** [comment]
Yes I'll take this.

**Comment by tomkerkhove** [comment]
Done for 2.0 in #193, previous version to follow

**Comment by ahmelsayed** [comment]
This is done for 1.5 and 1.4 in https://github.com/kedacore/keda-docs/pull/221

**Comment by tomkerkhove** [comment]
Thanks @ahmelsayed !
