### ISSUE TITLE
Transfer keda.sh DNS to CNCF

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#108]
Transfer keda.sh DNS to CNCF

**Comment by caniszczyk** [comment]
@tomkerkhove ideally we could just use Netlify DNS when LF owns the domain: https://app.netlify.com/teams/keda-7ntn70/dns

:)

**Comment by tomkerkhove** [comment]
Certainly but @jeffhollan owns it AFAIK

**Comment by tomkerkhove** [comment]
This seems to be done, ok to close @caniszczyk ?
