### ISSUE TITLE
Allow custom tolerance levels for ScaledObject

### ISSUE THREAD

**Issue by GautamSinghania** [kedacore/keda-docs#1100]
### Use-Case

We have a configuration for HPA called horizontal-pod-autoscaler-tolerance in [Kube Controller Manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/), defaulted to 0.1.

A `ScaledObject` should be able to set a custom value for this, overriding the default value. This has already been done for polling interval.

### Specification

Add an optional float field `tolerance` in `ScaledObject.spec`. This value must override the default value from Kube Controller Manager.

**Comment by GautamSinghania** [comment]
> @GautamSinghania this setting is set on K8s Controller level? Or is it a HPA setting that can be set on HPA resource? If the latter then we can add this option, but if it is something on a controller level, then we have no means to do that.
> 
> Could you point me to the specific documentation of this feature?

It is a controller level config. You can search for `horizontal-pod-autoscaler-tolerance` in [Kube Controller Manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/), it is defaulted to `0.1`.

If it cannot be handled by KEDA, please feel free to close this ticket. I have raised a parallel ticket in K8, see https://github.com/kubernetes/kubernetes/issues/116984.

**Comment by pierDipi** [comment]
@zroubalik @GautamSinghania now that the KEP implementation landed in 1.33 https://github.com/kubernetes/enhancements/pull/5078, should we re-open this issue so that KEDA exposes it in the ScaledObject API ?
