### ISSUE TITLE
Provide documentation on setting up authentication with GCP workload identity

### ISSUE THREAD

**Issue by raghu-manne** [kedacore/keda-docs#1112]
A clear documentation on how to set up workload identity

Would be good if a [reference](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to) or step by step guide on how to set up workload identity is added.

It is also unclear on which service account of keda setup should be used for setting up workload identity though we have only one service account. It can easily be understandable to a new comer if these things are explicitly mentioned in the documentation.

Referring to this link: https://keda.sh/docs/2.10/authentication-providers/gcp-workload-identity/

**Comment by raghu-manne** [comment]
@tomkerkhove 
Would love to work on this part of the documentation.

**Comment by tomkerkhove** [comment]
Wonderful, thank you!

**Comment by raghu-manne** [comment]
Made changes in PR #1120 and are merged to main.
Closing this issue.

**Comment by tomkerkhove** [comment]
Thank you!
