### ISSUE TITLE
What is KEDA webinar

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#113]
@jeffhollan & myself did a webinar on KEDA this week and was thinking it might be a good asset for on the website.
https://www.youtube.com/watch?v=Ax-_xo0OgVw

Thoughts?

We could add it next to the KubeCon session or introduce some "Getting Started"/"Learn More"

**Comment by zroubalik** [comment]
Great idea! I think that introducing a new section makes a perfect sense, so we can add more content in the future.

**Comment by tomkerkhove** [comment]
Will pick this up at some point

**Comment by tomkerkhove** [comment]
It's live - https://keda.sh/resources/#application-autoscaling-made-easy-with-kubernetes-event-driven-autoscaling-keda
