### ISSUE TITLE
Documented Prometheus Metric keda_scaler_activity is actually keda_scaler_active

### ISSUE THREAD

**Issue by rjduffner** [kedacore/keda-docs#1134]
The documentation for prometheus metrics references a metric called keda_scaler_activity. The metric is actually keda_scaler_active.

The documentation should be updated to reflect this.

I think it was just a typo between the app repo and the docs repo from here https://github.com/kedacore/keda/issues/4114

## Expected Behavior

Documentation should reference keda_scaler_active

## Actual Behavior

Documentation references keda_scaler_activity which does not exist

## Steps to Reproduce the Problem

Compare docs to code.

## Specifications

  - **KEDA Version:** 2.10.0
  - **Platform & Version:** Ubuntu 20.04 LTS
  - **Kubernetes Version:** 1.25
  - **Scaler(s):** N/A

**Comment by zroubalik** [comment]
Good catch! It is indeed a typo. Fixed, thanks.
