### ISSUE TITLE
Provide better description for the PAT permissions needed for the GitHub Runner scaler

### ISSUE THREAD

**Issue by olandese** [kedacore/keda-docs#1141]
Please provide in the documentation what are the minimal permission required for the Personal Access Token for the GitHub Runner Scaler (https://keda.sh/docs/2.10/scalers/github-runner/) to make the scaler work correctly.

**Comment by tomkerkhove** [comment]
@Eldarrin Can you help on this?

**Comment by Eldarrin** [comment]
Not tested it out, but this is the authentication requirements:
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/autoscaling-with-self-hosted-runners#authentication-requirements

I'll do some testing to check

**Comment by tomkerkhove** [comment]
Thanks! Once it is confirmed I'm happy to open a PR for the docs.
