### ISSUE TITLE
Why Azure Monitor Scaler metricName is deprecated 

### ISSUE THREAD

**Issue by lsolovey** [kedacore/keda-docs#1152]
KEDA documentation mentions that `metricName` is deprecated for Azure Monitor scaler.
https://keda.sh/docs/2.10/scalers/azure-monitor/

I understand there is a KEDA-wide effort to deprecate `metricName` (in a sense of KEDA metric name). 

But in this particular case for Azure Monitor, does this field rather represent the actual underlying Azure Monitor metric name? 

## Specifications

  - **KEDA Version:** 2.10
  - **Scaler(s):** Azure Monitor

**Comment by tomkerkhove** [comment]
This was changed in https://github.com/kedacore/keda-docs/pull/1074 but I think you are correct.

@JorTurFer @zroubalik any objection in reverting this?

**Comment by JorTurFer** [comment]
No from my side, we need to update keda code as well because you are right, in this scaler `metricName` is required because it's used for the underlying SKD

Are you willing to open the PRs removing this metric from deprecations?

**Comment by lsolovey** [comment]
> No from my side, we need to update keda code as well because you are right, in this scaler `metricName` is required because it's used for the underlying SKD
>
> Are you willing to open the PRs removing this metric from deprecations?

@JorTurFer Sure, I can do that. What version of `azure-monitor.md` doc should be updated? [2.11](https://github.com/kedacore/keda-docs/blob/main/content/docs/2.11/scalers/azure-monitor.md) or [2.10](https://github.com/kedacore/keda-docs/blob/main/content/docs/2.10/scalers/azure-monitor.md) ?

Also are you saying that we should update something in the keda code besides doc edits in `azure-monitor.md` ? Could you point me to what needs to be changed in the code? I'll see if I can do that as well.

**Comment by JorTurFer** [comment]
yeah, you should update docs v2.10 and 2.11.
in the code, you have to add the scaler in this condition:
 https://github.com/kedacore/keda/blob/739b770c8eecbfd0245cd76de02d25a3716d0900/controllers/keda/scaledobject_controller.go#L358-L360
