### ISSUE TITLE
Sample python code to process messages from rabbitmq 

### ISSUE THREAD

**Issue by pyjads** [kedacore/keda-docs#1257]
I am going over the keda scaling jobs documentation. 

![image](https://github.com/kedacore/keda-docs/assets/61117329/d78f2e23-a2a6-4981-b5f6-6d7083278e2b)

Could anyone please provide a sample code how this will be possible? I am not getting any clue on how I can poll only single message for processing. Will keda do it automatically and provide the message as the argument? or does the user have to write the logic to only poll single message from the queue?

Thank you in advance.

**Comment by JorTurFer** [comment]
Hello @pyjads 
You have to check the RabbitMQ SDK for the specific language to check how a single message can be read. KEDA doesn't peak any message from the queues, it just reads the queue metadata for getting the length, so the processing logic do need to stay in your workload side.
