### ISSUE TITLE
Unify contents of Community sections

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda-docs#127]
Community section on the main page is listing supporting companies:
<img width="1454" alt="Community - main page" src="https://user-images.githubusercontent.com/726523/78118504-65d0d780-7407-11ea-8d70-8266544319e2.png">

The separate Community page is missing this part:
<img width="1279" alt="Community - separate page" src="https://user-images.githubusercontent.com/726523/78118590-813be280-7407-11ea-8af5-086c76799eed.png">

Would be great to unify both contents.

**Comment by tomkerkhove** [comment]
I can take a look if you want? But will most probably be duplicated then unless @lucperkins has a more optimized way

**Comment by zroubalik** [comment]
@tomkerkhove it's up to you 😄  Per @lucperkins [comment](https://github.com/kedacore/keda-docs/pull/124#issuecomment-606819018) part of that page is already unifed and synced. I think it could be nice to sync the companies info as well.

**Comment by tomkerkhove** [comment]
Ok I won't be able to pull this off as they are configured here: https://github.com/kedacore/keda-docs/blob/master/config.toml#L232
