### ISSUE TITLE
Redesign how we present troubleshooting information

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda-docs#1270]
Currently, troubleshooting information is a bit fragmented across different pages:
- https://keda.sh/docs/2.12/troubleshooting/
- https://keda.sh/docs/2.12/faq/
- Scaler pages

Although all of them look as versioned, only the last one (scaler pages) is versioned, so we have different paged for serving the troubleshooting versions, some of them versioned, other not versioned...

I think that we should rethink this section to make it more usable and user friendly. IMHO it's a high value change because if the FAQ/troubleshooting information is easily discoverable, we can reduce the overhead answering to user questions and users will be more happy because they can solve the issues by themself.

My proposal is generating a troubleshooting section with all this information available and and in page search to look for info by keywords. This section can contain some subsections/pages:

- FAQ
- General 
- Scalers
	- Scaler that requires info
	- ...
- Auths
	- Auth that requires info
	- ....

**Comment by JorTurFer** [comment]
@tomkerkhove , we could include this as part of next round of work from CNCF?

**Comment by tomkerkhove** [comment]
Goal is to have it yet, project is associated

**Comment by nate-double-u** [comment]
I didn't catch that this had been closed. Is this work still needed?

**Comment by JorTurFer** [comment]
It was closed by inactivity but it's still required
