### ISSUE TITLE
Provide "Copy Link" button for FAQ questions

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#1274]
FAQ questions have anchors to which can be linked, but there is no simple way to copy the URL to it.

We should provide "Copy Link" button to make that simpler, similar to the categories:
![image](https://github.com/kedacore/keda-docs/assets/4345663/8d1b2add-7a8b-48a0-b4ab-99b08f140601)

**Comment by thisisobate** [comment]
Taking a look at this one...

**Comment by thisisobate** [comment]
@tomkerkhove what do you mean by anchors? Can you explain a bit more what you want to achieve here?
