### ISSUE TITLE
Scalers not shown on landing page

### ISSUE THREAD

**Issue by maxiangelo** [kedacore/keda-docs#1314]
### Report

Landing page scalers list is broken and does not show the type of scaler.
![image](https://github.com/kedacore/keda/assets/35735678/a5c0ceae-2e93-4d61-abe4-1d0743c46e5a)

It seems to me that the CSS is broken, it is configured to display: none 
If I disable that, it shows as expected.
![image](https://github.com/kedacore/keda/assets/35735678/6e482cdd-2dad-4bf0-9cd4-200d1bfc0153)

### Expected Behavior

Correct presentation of scaler list.
![image](https://github.com/kedacore/keda/assets/35735678/5f7719d5-c5c1-4dec-9e8f-96304a4dad56)

### Actual Behavior

Only footer of scaler card is shown
![image](https://github.com/kedacore/keda/assets/35735678/d79f1b48-64c1-4245-9fa6-7c24c9da3947)

### Steps to Reproduce the Problem

1. Go on https://keda.sh/
2. Scroll down 
3. Look at scalers

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

**Comment by zroubalik** [comment]
@maxiangelo thanks for reporting, you are right. Do you think you can try to fix it? Thanks!

**Comment by maxiangelo** [comment]
Hi, I think its caused by the recent commit #1303 

More  #specific, the part that was [added here](https://github.com/kedacore/keda-docs/commit/a82e9fe23c38cb5503a8b261f1f9e9eb41c74119#diff-3865b614c89a46a227346a201b03e48107cf9ce83b1f6fec40fc036245932945): 

```javascript
{{/* This logic expands collapsed section when URL is loaded in browser*/}}
<script>
  window.addEventListener(
    "DOMContentLoaded",
    () => {
      "use strict";
      const hash = (window.location.hash).slice(1);
      const cardContents = document.querySelectorAll(".card-content");
      cardContents.forEach((item) => {
        const id = item.getAttribute("id");
        if (hash === id) {
          item.style.display = "";
        } else {
          item.style.display = "none";
        }
      });
    });
</script>```

It appears that the function that the comparison of the hash and the ID fails.

**Comment by maxiangelo** [comment]
After a bit more investigation it seems like this feature is borked, hash and id are null.

I'm not even sure why this feature is needed anyway. I would suggest just removing it.

```
Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
(index):1737 Hash: 
(index):1737 Card ID: null
```

**Comment by zroubalik** [comment]
@thisisobate PTAL

**Comment by tomkerkhove** [comment]
Let's move the conversation for the fix to the PR @maxiangelo

**Comment by thisisobate** [comment]
oh...will take a look at this
