### ISSUE TITLE
CNCF Doc Tech Review

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#1333]
Cross-linking: https://github.com/cncf/techdocs/issues/87

**Comment by tomkerkhove** [comment]
Report is open on https://github.com/cncf/techdocs/pull/215/files

**Comment by tomkerkhove** [comment]
@kedacore/keda-maintainers I highly recommend reading the report!

I am super happy to read this, primarily on the governance:
![image](https://github.com/kedacore/keda-docs/assets/4345663/88dcbdcf-3630-4be6-a3f4-c63b59d569c6)

**Comment by JorTurFer** [comment]
will CNCF contribute with the refactor of the website or it's something that we have to address by ourself?
