### ISSUE TITLE
Reorganize the Documentation Table of Contents

### ISSUE THREAD

**Issue by dwelsch-esi** [kedacore/keda-docs#1362]
Reorganize the Table of Contents (TOC; the left-hand menu on the [documentation page](https://keda.sh/docs/2.13/)):

Among the benefits of this change are:

- Better welcome and orient new users
- Separate user roles (personas), if there are more than one 
- Improve findability and access to tasks and procedures
- Separate conceptual, task, and reference information

This issue tracks recommended changes resulting from an analysis of the KEDA documentation commissioned by [CNCF](https://www.cncf.io/projects/keda/). The analysis and supporting documents are here: https://github.com/cncf/techdocs/tree/main/assessments/0011-keda/

### Use-Case

Other issues describe reorganization to be done within the top-level sections of the TOC. For convenience, the issues are listed here.

- [ ] https://github.com/kedacore/keda-docs/issues/1363
- [ ] https://github.com/kedacore/keda-docs/issues/1364
- [ ] https://github.com/kedacore/keda-docs/issues/1365
- [x] https://github.com/kedacore/keda-docs/issues/1366

### Specification

Here is a proposed high-level outline for the tech doc Table of Contents. 

- [KEDA Concepts](https://keda.sh/docs/2.13/concepts/). See [Reorganize Concepts](https://github.com/cncf/techdocs/tree/main/assessments/0011-keda/keda-issues.md#issue-reorganize-concepts).
- [Getting Started (New users start here!)](https://keda.sh/docs/2.13/) (rename current "KEDA Documentation" heading). See [Write a "Getting Started" Guide](https://github.com/cncf/techdocs/tree/main/assessments/0011-keda/keda-issues.md#issue-write-a-getting-started-guide).
- [Using KEDA or Operator Guide](https://keda.sh/docs/2.13/operate/) (rename current "Operate"). See [Update the Operator Guide](https://github.com/cncf/techdocs/tree/main/assessments/0011-keda/keda-issues.md#issue-update-the-operator-guide).
- Reference. See [Create a Reference](https://github.com/cncf/techdocs/tree/main/assessments/0011-keda/keda-issues.md#issue-create-a-reference-topic).
- [Scalers](https://keda.sh/docs/2.13/scalers/).

**Comment by nate-double-u** [comment]
I'm not sure this has been completed, if it was just the bit that closed this could we reopen it?
