### ISSUE TITLE
Create a Reference Topic

### ISSUE THREAD

**Issue by dwelsch-esi** [kedacore/keda-docs#1366]
Create a top-level table of contents (TOC) heading and reorganize the documentation so that this section contains all reference pages. 

Elsewhere in the documentation where the user needs reference information (for example, to choose a specific configuration value or to check the syntax of a command), link to the appropriate reference page. 

This issue tracks recommended changes resulting from an analysis of the KEDA documentation commissioned by [CNCF](https://www.cncf.io/projects/keda/). The analysis and supporting documents are here: https://github.com/cncf/techdocs/tree/main/assessments/0011-keda/

### Use-Case

Some typical types of reference pages include:
- API specifications
- CLI specifications
- Configuration options

Specifically for KEDA:

- The Reference section should be at or near the end of the ToC
- Include the following information in the Reference section:
  - Move the FAQ to the Reference section.
  - Add a glossary to the Reference section.

### Specification

Here is a proposed outline. Links are to existing pages that can be used as-is or provide a starting point. 

- Reference
  - [Authentication Providers](https://keda.sh/docs/2.13/authentication-providers/)
    - [AWS (IRSA) Pod Identity Webhook](https://keda.sh/docs/2.13/authentication-providers/aws/)
    - ...
    - [Secret](https://keda.sh/docs/2.13/authentication-providers/secret/)
  - Scaled Object specification (from "Concepts"; https://keda.sh/docs/2.13/concepts/scaling-deployments/#scaledobject-spec)
  - ScaledJob specification (https://keda.sh/docs/2.13/concepts/scaling-jobs/#scaledjob-spec)
  - [Events](https://keda.sh/docs/2.13/operate/events/)
  - [Firewall requirements](https://keda.sh/docs/2.13/operate/cluster/#firewall)
  - ...
  - [FAQ](https://keda.sh/docs/2.13/faq/)
  - Glossary

**Comment by nate-double-u** [comment]
This is actively being worked on in https://github.com/kedacore/keda-docs/pull/1389
