### ISSUE TITLE
Write a Glossary

### ISSUE THREAD

**Issue by dwelsch-esi** [kedacore/keda-docs#1367]
Create a glossary of terms specific to KEDA. Also include key Kubernetes terms that are vital to understanding KEDA. The glossary also spells out acronyms. 

Add the glossary to the Reference section. Where a glossary term is used in the documentation, link to the definition in the glossary.

This issue tracks recommended changes resulting from an analysis of the KEDA documentation commissioned by [CNCF](https://www.cncf.io/projects/keda/). The analysis and supporting documents are here: https://github.com/cncf/techdocs/tree/main/assessments/0011-keda/

### Use-Case

The primary purpose of a glossary is to define terms so that a reader can understand the documentation as they read it; without this information, either a reader's understanding is incomplete or they have to intrusively interrupt their reading to look up a term on the internet. Even better, if supported by the web framework, is if the term is available via mouse-over contextual help.

### Specification

For an example from another CNCF project, see the [glossary in the Backstage documentation](https://backstage.io/docs/references/glossary/).

Here is a partial list of terms to include:

- Admission Webhook
- Agent
- Cluster
- CRD
- Event
- Event Source
- Grafana
- GRPC
- HPA
- KEDA
- Metrics
- OpenTelemetry
- Operator
- Prometheus
- Scaled Object
- Scaled Job
- Scaler
- Stateful Set
- TLS
- Webhook

**Comment by nate-double-u** [comment]
This is actively being worked on in https://github.com/kedacore/keda-docs/pull/1389
