### ISSUE TITLE
Write a Procedure for Setting Up a Scaler

### ISSUE THREAD

**Issue by dwelsch-esi** [kedacore/keda-docs#1368]
Write a procedure for setting up a scaler for KEDA. Include all steps that are common to any scaler. Supplemental instructions specific to particular scalers can be elsewhere.

This procedure is fundamental to using KEDA and should go at or near the beginning of the Operator's Guide.

### Use-Case

Setting up a scaler seems to be largely a matter of installing the scaler and providing parameters in a configuration file. While the configurations are provided for all the various scalers, there doesn't seem to be a description of the procedure for doing the basic setup. This should go at the top of the Operator guide. 

Users should be able to follow the procedure for any (or at least most) scalers. Any scaler that requires special instructions other than the configuration file should have its own procedure page, listing the extra steps required.

### Specification

Write complete, step-by-step instructions. Don't assume the user knows anything. For example, name the configuration file and tell users where to put it, even if this is common knowledge. This is the generic template they'll use to set up any scaler, including their first.

**Comment by shubhusion** [comment]
Hi @dwelsch-esi and @tomkerkhove,

Could you please assign this issue to me? I would like to contribute to it. I have applied for the TUF documentation project through the Linux Foundation.

Thank you!

**Comment by nate-double-u** [comment]
Hi @shubhusion, I appreciate your enthusiasm, but the selections haven't been made yet for LFX Mentorship 2024 Term 2. Assigning someone before the announcements go out would be premature.

**Comment by zroubalik** [comment]
@shubhusion we would be happy to assign this issue to you, if you are still interested.

**Comment by shubhusion** [comment]
> @shubhusion we would be happy to assign this issue to you, if you are still interested.

Yeah I am interested. Can you also provide me resources to get started.

**Comment by shubhusion** [comment]
@zroubalik Procedure needs to be updates in version 2.15 or 2.14 ?

**Comment by zroubalik** [comment]
@shubhusion I think that the content will be the same for both versions, so it's a low effort to update both versions, thanks :)

**Comment by shubhusion** [comment]
> @shubhusion I think that the content will be the same for both versions, so it's a low effort to update both versions, thanks :)

Hi @zroubalik, Could you please guide me a little? I am new to this repository 
I have updated version 2.14 rn which other version do I need to update?

**Comment by shubhusion** [comment]
@zroubalik @tomkerkhove can you please assign this issue to me ? I have already made a PR

**Comment by nate-double-u** [comment]
I'm not sure this has been completed, if it was just the bot that closed this could we reopen it?

**Comment by shubhusion** [comment]
> I'm not sure this has been completed, if it was just the bot that closed this could we reopen it?

@nate-double-u PR has been completed. It was initially reviewed by @zroubalik, and I made changes based on his feedback. 

@zroubalik @nate-double-u can check and merge

**Comment by nate-double-u** [comment]
> > I'm not sure this has been completed, if it was just the bot that closed this could we reopen it?
> 
> @nate-double-u PR has been completed. It was initially reviewed by @zroubalik, and I made changes based on his feedback.
> 
> @zroubalik @nate-double-u can check and merge

If it's done, great! I just didn't want the issue auto-closed by bot 😊
