### ISSUE TITLE
Update diagram

### ISSUE THREAD

**Issue by yaron2** [kedacore/keda-docs#138]
Kubernetes store should be Kubernetes API server in the diagram

**Comment by zroubalik** [comment]
Agree, we should fix diagrm as `Kubernetes API Server` is more suitable naming.

**Comment by tomkerkhove** [comment]
In here you mean?
![image](https://user-images.githubusercontent.com/4345663/78864182-6dadfe80-7a3b-11ea-9bc2-8f72b97ba253.png)
[source](https://github.com/kedacore/keda-docs/blob/master/schematics.pptx)

If so, I can pick that up.

**Comment by zroubalik** [comment]
@tomkerkhove yes! thx
