### ISSUE TITLE
Doc: Pubsub scaler, document relation between stabilizationWindowSeconds and metrics sample rate

### ISSUE THREAD

**Issue by ls-urs-keller** [kedacore/keda-docs#1439]
https://github.com/kedacore/keda-docs/blob/c01eb795c151838f559a486219e2e79bdab36daa/content/docs/2.14/scalers/gcp-pub-sub.md?plain=1#L35

I'm wondering if you can document a recommendation for the value of  `stabilizationWindowSeconds` given that the underlying pubsub metrics are sampled only every 60s and can take up to 120s to update.

Otherwise, this might unnecessarily scale to the max due to the rate at which the metric updates

**Comment by zroubalik** [comment]
@ls-urs-keller makes sense, are you willing to update docs with the details?
