### ISSUE TITLE
KEDA documentation around number of replicas supported for metrics server is contradictory

### ISSUE THREAD

**Issue by lantingchiang** [kedacore/keda-docs#1450]
Under https://keda.sh/docs/2.14/operate/cluster/#high-availability, there is a table like so:
<img width="961" alt="Screenshot 2024-07-11 at 4 35 01 PM" src="https://github.com/kedacore/keda/assets/49918461/d1f3da5d-2ba4-4a03-8e17-eae79613663d">

For the "Metrics Server" deployment, the "Support Replicas" column has the value "1", which reads as only one replica is supported. However, the "Note" column mentions that "You can run multiple replicas of our metrics sever", which indicates that multiple replicas are supported.

It should be clarified exactly how many replicas are supported and perhaps the language for the "Support Replicas" column should be updated.

**Comment by tomkerkhove** [comment]
I think we are good to close, no?
