### ISSUE TITLE
does KEDA works with azure BLOB trigger function app??

### ISSUE THREAD

**Issue by jainshikha** [kedacore/keda-docs#164]
Created the blob azure function and tried to deploy it on minikube KEDA, am unable to see the HPA for blob trigger.
tried to use the YMl provided in :
https://keda.sh/scalers/azure-storage-blob/

**Comment by tomkerkhove** [comment]
I think this is more of an Azure Function question, no?

**Comment by ahmelsayed** [comment]
It is. The blob scaler should work with the one caveat mentioned in the notice  https://keda.sh/docs/1.4/scalers/azure-storage-blob/ 

> As of now, this Azure Blob Storage scaler scales based on the count of the blobs in a container as opposed to the Azure Functions behavior where code is only triggered on new blobs.

Meaning you have to delete the blob after processing for it to work correctly. If you're not seeing any scaling happen then it can either be an azure functions tooling issue or a keda scaler issue. 

The keda logs should point at the issue if you can get them `kubectl logs <keda-operator-pod> -n keda`

**Comment by jainshikha** [comment]
we can close the issue azure blob functions are working fine with KEDA when we move the files form blob
