### ISSUE TITLE
Duplicate scalers are listed on home page

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#167]
Duplicate scalers are listed on home page when using multiple versions of our docs.

**Comment by tomkerkhove** [comment]
Is this something you can have a look at @lucperkins?

Sorry but looks like it slipped through in #151

**Comment by lucperkins** [comment]
@tomkerkhove Can you clarify? I'm not seeing an issue.

**Comment by zroubalik** [comment]
@tomkerkhove home page is fixed, but there's the same issue on the scalers page: https://keda.sh/docs/1.4/scalers/

See buttons in the `Currently available schedulers for KEDA` sections

**Comment by lucperkins** [comment]
A clarification: the goal of my work is primarily to put CNCF project maintainers in a position to succeed longer term with their site/docs. Thus far I’ve addressed problems as they’ve come up, but the intention is more for KEDA maintainers to be able to address these issues on their own over time. Could one of you perhaps attempt to address this issue first?

**Comment by tomkerkhove** [comment]
I'm already working on it as @zroubalik mentioned but we're no experts so cannot guarantee we won't need your skills for this 😁

**Comment by tomkerkhove** [comment]
Unfortunately it looks like I'll need your help as I'm not able to figure out how to determine the versions. Once I have those, I can get the job done.

This is what I have now - https://github.com/kedacore/keda-docs/pull/195

**Comment by lucperkins** [comment]
@tomkerkhove Could you clarify what the issue is? I'm not seeing duplicated scalers on the home page.
