### ISSUE TITLE
https://keda.sh/docs/deploy/ link is broken

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda-docs#174]
It was used in the https://github.com/kedacore/keda#deploying-keda to point users to the deployment option. This bug was brought be introducing versioned docs.

https://keda.sh/docs/deploy/ could link to the latests docs

**Comment by tomkerkhove** [comment]
A redirect for this would be ideal actually!

**Comment by lucperkins** [comment]
@tomkerkhove You shouldn't need a redirect for this. Just change the URL to https://keda.sh/docs/latest/deploy.

**Comment by tomkerkhove** [comment]
That's good to hear; thanks!

**Comment by zroubalik** [comment]
Fixed!
