### ISSUE TITLE
Links on index page to Concepts, Architecture,... are broken

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda-docs#179]
https://keda.sh/ ->
Links in the main section on the index page, (white buttons) are broken.
`Concepts, Deploying KEDA, Architecture, Scalers, Blog`

Probably because of migration to versioned docs.

**Comment by zroubalik** [comment]
@lucperkins could you please look at that?

**Comment by lucperkins** [comment]
You just need to update the links to the latest docs

**Comment by jeffhollan** [comment]
Yes seeing this too - now the docs are behind a version path like this
`https://keda.sh/docs/1.4/deploy/`
but the homepage links to
`/docs/deploy`

@tomkerkhove not sure if there is a way to redirect to a default version but this seems to be related to your version changes

**Comment by jeffhollan** [comment]
I'm working on a quick mitigation to this by hardcoding in version 1.4 but we'll have to explore how this will work long term. PR incoming...

**Comment by lucperkins** [comment]
@jeffhollan You don't need to hardcode. You can use `/docs/latest/*`.
