### ISSUE TITLE
dead link Docs > Operate

### ISSUE THREAD

**Issue by mavrick** [kedacore/keda-docs#249]
https://keda.sh/docs/1.5/operate/

The 404 page also lists links that just link back to itself.

dead link from the menu:
![image](https://user-images.githubusercontent.com/357659/92699829-68a9fe00-f391-11ea-9468-b04b3b1e8863.png)

**Comment by tomkerkhove** [comment]
That's because it's only introduced in 2.0, will see if we can only show this for a given version but I'm not sure.

**Comment by mavrick** [comment]
well well well, it works now ;)
