### ISSUE TITLE
YAML deployment instructions fail with a 404 error

### ISSUE THREAD

**Issue by iamalexmang** [kedacore/keda-docs#267]
As per `content/docs/2.0/deploy.md`, 'If you want to try KEDA [...] you can still deploy it with kubectl'.

Seems that the YAML manifest referenced though is returning a 404 HTTP status code (https://github.com/kedacore/keda/releases/download/v2.0.0/keda-2.0.0.yaml).

**Comment by tomkerkhove** [comment]
Thanks for the report! It's fixed in https://github.com/kedacore/keda-docs/pull/268.

You can do `kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.0.0-beta/keda-2.0.0-beta.yaml`
