### ISSUE TITLE
Bug: Wrong link to scaler code in documentation

### ISSUE THREAD

**Issue by spoplavskiy** [kedacore/keda-docs#280]
The auto generated website with scaler documentation pointing to a wrong branch, when you click a "scaler code" button.

As an example:
On [Log Analytics Scaler](https://keda.sh/docs/2.0/scalers/azure-log-analytics/) web page "scaler source" button points to this page: https://github.com/kedacore/keda/blob/master/pkg/scalers/azure_log_analytics_scaler.go
But should point to this page: https://github.com/kedacore/keda/blob/v2/pkg/scalers/azure_log_analytics_scaler.go

The difference is in branch name.

**Comment by zroubalik** [comment]
Good catch, this should be fixed, but we are planning to rename v2 branch back once 2.0 is out, so we can wait for a wihle.

**Comment by tomkerkhove** [comment]
Closing since this is fixed.
