### ISSUE TITLE
AWS SQS sample has a syntax error

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda-docs#290]
Hey ! Shouldn't the `TriggerAuthentication.spec.SecretTargetRef.Name` point to the name of the secret where AWS creds are? In this case, it should be "test-secrets" rather than "keda-aws-secrets", right? https://keda.sh/docs/2.0/scalers/aws-sqs/#authentication-parameters

**Comment by jeffhollan** [comment]
Text was flagged from the slack channel.  Need to update the example

**Comment by tomkerkhove** [comment]
Jup, it should. THanks for hte PR!
