### ISSUE TITLE
Should we list who's supporting KEDA?

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#30]
Should we list who's supporting KEDA?

In the main repo we have listed Microsoft & Red Hat which we might want to list in the community section as well? If other companies, let's say AWS, contribute we can add them as well.

**Comment by jeffhollan** [comment]
Yeah we could likely add a “members” fragment to the root page and for now just red hat and Microsoft (and Codit)

**Comment by tomkerkhove** [comment]
That sounds good to me but we should keep the list brief so that the landing page doesn't get too long, or not?

Open to anything

**Comment by jeffhollan** [comment]
Yeah either way. Even if you have your own side company. I don’t mind if we include other orgs that have provided significant impact or investment. Up to you but I’m on with it

**Comment by tomkerkhove** [comment]
Sure, I'll have a look at this
