### ISSUE TITLE
Documentation for AWS credentials is very hard to understand

### ISSUE THREAD

**Issue by trondhindenes** [kedacore/keda-docs#314]
Before I post my comment, I do want to emphasise that I'm quite well versed in AWS and Kubernetes. Still, I'm having a very hard time understanding parts of the Keda documentation.

Sentences like "identityOwner - Receive permissions on the CloudWatch via Pod Identity or from the KEDA operator itself (see below)." - which pod are we talking about here? Isn't the keda operator running in a pod? When would I use the various options?

In the section https://keda.sh/docs/1.4/scalers/aws-sqs/#authentication-parameters it's not clear if these attributes should be set directly on the `ScaledObject` object, or if they go on a `TriggerAuthentication`. A more complete documentation with better examples would go a long way.

The only actual example is a very basic scenario of using hard-coded access key/secret - a scenario I believe is pretty uncommon to use in production.

It would be good if:
- The documentation was clarified
- Example were provided for using kiam-based or eks-based authentication
- The documentation would be clearer on where attributes should be put - `ScaledObject` or `TriggerAuthentication`.

I'd be more than happy to submit a PR to fix some of this, but I honestly don't understand the intention behind the `identityOwner` stuff, so ATM it's a little difficult for me to provide more than an issue.

**Comment by tomkerkhove** [comment]
I'll come back to your feedback asap, this is very valuable; thanks for reporting!

**Comment by tomkerkhove** [comment]
I don't have experience with AWS but will try to answer your questions:

> Sentences like "identityOwner - Receive permissions on the CloudWatch via Pod Identity or from the KEDA operator itself (see below)." - which pod are we talking about here? Isn't the keda operator running in a pod? When would I use the various options?

Unfortunately this is AWS specific so can't help, sorry.

> In the section [keda.sh/docs/1.4/scalers/aws-sqs/#authentication-parameters](https://keda.sh/docs/1.4/scalers/aws-sqs/#authentication-parameters) it's not clear if these attributes should be set directly on the `ScaledObject` object, or if they go on a `TriggerAuthentication`. A more complete documentation with better examples would go a long way.

Authentication parameters are only supported on `TriggerAuthentication` where you can use these options.

> To add to this, on this page: [keda.sh/docs/2.0/concepts/authentication](https://keda.sh/docs/2.0/concepts/authentication/)
> "By using that identity, you can defer authentication to the pod & the service provider, rather than configuring secrets" again - this is confusing, since it doesn't state _which_ pod it's referring to.

In this case, this is the KEDA operator which will handle the authentication with the service provider (in this case AWS).

> From what I can see after looking at how Keda behaves:
> If the `identityOwner` is set to pod, and type we're using kiam, it looks like the keda metrics pod tries to call AssumeRole on the role specified in the scale target deployment. That's a neat implementation and a valuable option to have, but the documentation doesn't even come close to covering the necessary staps and required configuration on the aws iam side.
> 
> I'd be happy to try and help out with documentation here, but it would be good to hear back from the implementation author that I'm understanding the implementation correctly, as all I've done is looking at error logs to try and understand how this works.

Maybe @nisan270390 can help here who implemented this

**Comment by trondhindenes** [comment]
Thanks! I think I understand - will poke a bit in the codebase aswell just to confirm my theories.

**Comment by rangarb885** [comment]
I agree with @trondhindenes  point on `The only actual example is a very basic scenario of using hard-coded access key/secret - a scenario I believe is pretty uncommon to use in production.`

Unfortunately I don't have a go to page on Keda documentation to implement aws-eks based trigger setup. I
Can we have a complete example (including role, role-binding, sa requirements) for setting up KEDA (example SQS Scalar) in AWS EKS 1.21 using aws-eks as authentication mechanism. 

My personal experience : I was successful to do this aws-eks based setup, but it failed to scale and left no clue where the gap is.. Though the metrics were reported and was visible on HPA , scaling never triggered.

**Comment by tomkerkhove** [comment]
I'd be happy to help and write a walkthrough, but unfortunately I have no experience with AWS.

Once #1408 is resolved, are you up for contributing it?

**Comment by rangarb885** [comment]
Sure @tomkerkhove

**Comment by alexgleith** [comment]
Hey @rangarb885 can you please provide some information here about how you're using it? We're trying to get role-based authentication working right now!

**Comment by rangarb885** [comment]
Hi @alexgleith: The easiest and quicker way to grant access for Keda to work with AWS SQS is to annotate the `keda-operator` service-account with AWS IAM role.  Let me put down the steps:

Prerequisites for below write-up:

1.  Make sure OIDC is enabled on EKS cluster. [Ref. AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html)
2. keda is installed(will be installed) on `keda` namespace with yaml files or Helm provided by Keda team.
3. You have access to AWS and EKS as admin or your tooling has that access.
4. EKS 1.21 (I think this should work for EKS 1.16 onwards) with Keda 2.4.0 

**AWS IAM Setup:**

**Create an IAM role in AWS which trust the `keda-operator` service account in EKS.**

Example IAM Role named `keda-operator-role` : 

_IAM Policy to grant SQS Readonly access_ : 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl",
                "sqs:ListDeadLetterSourceQueues",
                "sqs:ListQueues"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```
_Trusted Relationship_ 

- AWS_ACCOUNT_ID => Your AWS Account ID
- OIDC_PROVIDER_ID_FROM_EKS => `AWS Console -> EKS -> Details -> OpenID Connect provider URL` . 
Copy the last part on the url which will be alpha-numeric ID  (32 chars)
- EKS_WORKER_IAM_ROLE_ARN => The IAM role which is attached to your EKS worker nodes.
 

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::<AWS_ACCOUNT_ID>:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/<OIDC_PROVIDER_ID_FROM_EKS>"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.us-west-2.amazonaws.com/id/<OIDC_PROVIDER_ID_FROM_EKS>:aud": "sts.amazonaws.com",
          "oidc.eks.us-west-2.amazonaws.com/id/<OIDC_PROVIDER_ID_FROM_EKS>:sub": "system:serviceaccount:keda:keda-operator"
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "<EKS_WORKER_IAM_ROLE_ARN>"
      },
      "Action": "sts:AssumeRole",
      "Condition": {}
    }
  ]
}
```

**Annotate the `keda-operator` service account with the above created IAM role.**

```
eks.amazonaws.com/role-arn: <keda-operator-role-arn>
eks.amazonaws.com/audience: sts.amazonaws.com
```

If you are doing the keda setup using helm, you can add these annotation under `serviceAccount.annotations` via `set` in command line or set them in `values.yaml` file. 

If you want to do this via [kubectl](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#annotate) on an existing keda installation, you can use the below command lines:

```
kubectl -n keda  annotate serviceaccount keda-operator eks.amazonaws.com/role-arn=<keda-operator-role-arn>
kubectl -n keda  annotate serviceaccount keda-operator eks.amazonaws.com/audience=sts.amazonaws.com
```

**Scaled Object**

Under the SQS scalar configuration for a specific deployment, you need to set `identityOwner` as `operator` (default is pod). 

As per [Keda docs](https://keda.sh/docs/2.3/scalers/aws-sqs/)
> The only requirement is that the Keda operator has the correct IAM permissions on the SQS queue. Additional Authentication Parameters are not required.

**Deployment**
No change required as Scaling related authentication is handled within keda-operator

**Comment by tomkerkhove** [comment]
Sounds like a great plan, thanks for proposing @rangarb885!

You can find our contribution guide on https://github.com/kedacore/keda-docs/blob/master/CONTRIBUTING.md and typically this information gets added to the scaler page but I see 2 other options here:
- Extend https://keda.sh/docs/2.4/concepts/authentication/#pod-authentication-providers
- Blog post
What do you think @zroubalik ?

**Comment by trondhindenes** [comment]
@rangarb885 I'm pretty sure you don't need the `sts:AssumeRole` statement.
One way to find the correct statement is to use `eksctl` and look at the generated role and policies:

`eksctl create iamserviceaccount --name my-keda-thing --region="$REGION" --cluster "$CLUSTERNAME" --attach-policy-arn "$POLICY_ARN" --approve --override-existing-serviceaccounts`  (more doc at https://eksctl.io/usage/iamserviceaccounts/)

Might be worth mentioning `eksctl` as an option for creating the iam role/serviceaccount in the docs as well. It's probably the easiest way to create iam-role-linked-serviceaccounts on EKS.

**Comment by zroubalik** [comment]
> What do you think @zroubalik ?

I think that extending the pod authentication providers is better from a visibility for users (and maybe link that from the AWS scaler docs as well).

**Comment by TiagoGoddard** [comment]
> **Annotate the `keda-operator` service account with the above created IAM role.**
> 
> ```
> eks.amazonaws.com/role-arn: <keda-operator-role-arn>
> eks.amazonaws.com/audience: sts.amazonaws.com
> ```

Do keep in mind that the annotation to `eks.amazonaws.com/audience` isn't required when it's set to `sts.amazonaws.com` because that is it's default value.

Also, I wasn't able to find a reference for the `identityOwner` with value `aws-eks` for AWS CloudWatch Scaler, but it does seem to accept it.

**Comment by TiagoGoddard** [comment]
I'll see what I can do. Right now, I'm trying to understand the internal working of KEDA and the AWS CloudWatch scaler. Still, I'll probably contribute to the documentation, especially the authentication part, if I can make head or tails of it.

**Comment by TNonet** [comment]
I am struggling to get the instructions listed out by @rangarb885 to work. I have listed out my steps in this discussion: https://github.com/kedacore/keda/discussions/2912#discussioncomment-6755958

**Comment by TNonet** [comment]
> I am struggling to get the instructions listed out by @rangarb885 to work. I have listed out my steps in this discussion: [kedacore/keda#2912 (comment)](https://github.com/kedacore/keda/discussions/2912#discussioncomment-6755958)

You need to restart the keda-operator pod after annotating the SA.

**Comment by tomkerkhove** [comment]
Any improvements we can make to our existing docs to help @TNonet? Always happy to review a PR!

**Comment by seancallaway** [comment]
When I followed the instructions above, I found that the IAM role applied to my EKS managed node groups was actually what needed those permissions. After adding the policy to that role, my scaler worked correctly.

It should be noted that the policy is _also_ applied to the role assumed by the `keda-operator` ServiceAccount.

**Comment by trondhindenes** [comment]
> When I followed the instructions above, I found that the IAM role applied to my EKS managed node groups was actually what needed those permissions. 

That means that ever pod running on that node group will have the same access as KEDA, certainly not least-privelige. I would recommend using a dedicated service account/iam role (IRSA)
