### ISSUE TITLE
keda.k8s.io -> keda.sh in entire doc

### ISSUE THREAD

**Issue by didier-durand** [kedacore/keda-docs#319]
Hi there,

Running https://github.com/kedacore/keda-docs/search?q=keda.k8s.io shows that there is still a lot of references to `keda.k8s.io` in the doc.

For 2.0, I understand that it should be changed to `keda.sh`

I am happy to do this work through a PR. Please, let me know.

Didier

**Comment by tomkerkhove** [comment]
That would be a great PR, thanks!

**Comment by didier-durand** [comment]
You're welcome!
Ok, I'll do that.

**Comment by didier-durand** [comment]
I did the whole review: indeed, the only mentions of keda.k8s.io appear in branches for versions < 2.0. For 2.0 & 2.1, the branches contain only keda.sh

So, all good!

Closing

Didier

**Comment by tomkerkhove** [comment]
No problem and thanks for cehcking!
