### ISSUE TITLE
Kafka Scaling Doc update 

### ISSUE THREAD

**Issue by rindoze** [kedacore/keda-docs#322]
I had been stumped by a Kafka scaler that wouldn't scale up to my target maxReplicaCount. 
After investigation it turned out that the replicas will not exceed the number of partitions on a topic.
This is good behavior, as additional replicas above the partition count would not do anything; however, I could not find any documentation that mentioned this upper bound.
It would be helpful to add this to the Kafka scaler documentation.

**Comment by tomkerkhove** [comment]
Definately needs to be documented; would you mind sending a PR please?

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove  I didn't find any NOTE about it on the Kafka doc. should I create a PR on it?

**Comment by tomkerkhove** [comment]
It's been a while, what note are you referring to?

**Comment by Ritikaa96** [comment]
@tomkerkhove About this one in case such confusion occur again:
>>This is good behavior, as additional replicas above the partition count would not do anything; however, I could not find any documentation that mentioned this upper bound.
>>

**Comment by tomkerkhove** [comment]
We are definately open for doc improvements on that, thanks!

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove, Thanks for the go-ahead. I've created a PR : #363 for the issue.
