### ISSUE TITLE
Introduce latest version for FAQ & troubleshooting

### ISSUE THREAD

**Issue by Shubham82** [kedacore/keda-docs#362]
When I am trying to fix the link in README.md but i have some doubt in it i.e. in [this](https://github.com/kedacore/keda-docs#adding-scaler-documentation) the scaler redirect the page of faq to 2.0, i want to change it to 2.1 i.e. latest one. one method is that i put 2.1 in the link like this` https://keda.sh/docs/2.1/faq/`  and same with the  troubleshooting page in  [this](https://github.com/kedacore/keda-docs#add-new-troubleshooting-guidance) also which is currently a dead link. but in that we have to change it for every version,  the second method i followed which is used  for scaler in [this](https://github.com/kedacore/keda-docs#adding-scaler-documentation) i.e. `https://keda.sh/docs/scalers` but when i tried to do  that for faq and troubleshooting like this `https://keda.sh/docs/faq `and `https://keda.sh/docs/troubleshooting` respectively it give me a dead link error. also see the url  in config.toml for faq and troubleshooting [here](https://github.com/kedacore/keda-docs/blob/cf4745bbb9a7829437391ca7b5b49d883f94a167/config.toml#L172) and [here](https://github.com/kedacore/keda-docs/blob/cf4745bbb9a7829437391ca7b5b49d883f94a167/config.toml#L178)  which same as for [scaler](https://github.com/kedacore/keda-docs/blob/cf4745bbb9a7829437391ca7b5b49d883f94a167/config.toml#L123). Did i miss something, or it is working as mention in the first method. Just confirming things before creating the PR for it. 

Any help would be appreciated!

**Comment by Shubham82** [comment]
Hi @tomkerkhove @zroubalik 
Could you please take a look.

Thanks.

**Comment by tomkerkhove** [comment]
I'm not sure if I'm following, so the issue you are having is that https://keda.sh/docs/faq and https://keda.sh/docs/troubleshooting are dead links?

**Comment by Shubham82** [comment]
yes, they are the dead links.  

Current links:
faq     `https://keda.sh/docs/2.0/faq/`   --> link to previous document not the latest one.
troubleshooting    `https://keda.sh/docs/troubleshooting`  --> dead link.

workaround:
faq     ` https://keda.sh/docs/2.1/faq/` 
troubleshooting: `https://keda.sh/docs/2.1/troubleshooting/`

This is specific to version. i want to do like way which is done in scaler: ` https://keda.sh/docs/scalers`  always point to the latest one. Same thing for faq and troubleshooting.
 
 It is mention In config.toml for faq and troubleshooting [here](https://github.com/kedacore/keda-docs/blob/cf4745bbb9a7829437391ca7b5b49d883f94a167/config.toml#L172) and [here](https://github.com/kedacore/keda-docs/blob/cf4745bbb9a7829437391ca7b5b49d883f94a167/config.toml#L178)  

Thanks

**Comment by tomkerkhove** [comment]
For now the workaround is required, but we should introduce a latest for them as well.

**Comment by Shubham82** [comment]
ohk, For now i will create a pr for that.
Thanks for title.

**Comment by Shubham82** [comment]
any suggestion what we have to do for latest version as it is mention in config.toml still it is not using that.
it help me  in investigating the things.

**Comment by Shubham82** [comment]
@tomkerkhove  one more thing should i also modify this
`cp -rf content/docs/2.0.0 content/docs/2.1.0` to  ` cp -rf content/docs/<CurrentVersion> content/docs/<NewVersion>`  in[ Working with documentation versions](https://github.com/kedacore/keda-docs#working-with-documentation-versions)  It seems specific not general.

**Comment by tomkerkhove** [comment]
> @tomkerkhove one more thing should i also modify this
> `cp -rf content/docs/2.0.0 content/docs/2.1.0` to ` cp -rf content/docs/<CurrentVersion> content/docs/<NewVersion>` in[ Working with documentation versions](https://github.com/kedacore/keda-docs#working-with-documentation-versions) It seems specific not general.

Sounds good to me, thanks!

**Comment by tomkerkhove** [comment]
I'll take a look at this since I think we just have to add it here:
https://github.com/kedacore/keda-docs/blob/master/layouts/index.redirects

Unless you want to give this a go first @Shubham82?

**Comment by Shubham82** [comment]
I would a like to work on it.
Thanks a lot @tomkerkhove

**Comment by Shubham82** [comment]
I have created a PR for it in #365
