### ISSUE TITLE
TLS Secret from Env for Redis List scaler

### ISSUE THREAD

**Issue by normkatz** [kedacore/keda-docs#378]
For [Redis List trigger](https://keda.sh/docs/2.1/scalers/redis-lists/), you have:
enableTLS and I'm assuming the TLS key would be specified here:

authenticationRef:
      name: keda-trigger-auth-redis-secret

For password, you allow passwordFromEnv but I don't think you support redisSecretFromEnv yet.

Can you confirm both of the above and any plans to support Secret from Env?

**Comment by tomkerkhove** [comment]
Good question, maybe @goku321 can elaborate concerning `useTLS` because I'm not sure if you have to specify something
