### ISSUE TITLE
Fix documentation to point to right Yaml files 

### ISSUE THREAD

**Issue by pragnagopa** [kedacore/keda-docs#396]
Files mentioned  in https://keda.sh/docs/1.4/deploy/#yaml

- deploy/crds/keda.k8s.io_triggerauthentications_crd.yaml
- deploy/crds/keda.k8s.io_scaledobjects_crd.yaml

do not exist in `main` branch. Update docs to point to right files in V1

**Comment by joshi-aparna** [comment]
I believe this issue could be closed now.
