### ISSUE TITLE
Improve scaler catalog to be more user-friendly

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#412]
Over time, our scaler catalog has grown a lot over the last couple of releases where we have more than 30 of them today.

As a user, it's not that easy anymore to find the scalers you need and the navigation is not able to coop with it.

It would be good if we can:
- Make the navigation be more user-friendly in this case
- Integrate external scalers from the community to create a central place for all scalers (built-in or 3rd party)
- Provide filtering on the current overview, examples are:
  - Categories (ie messaging, databases, CI/CD)
  - Cloud (Alibaba, AWS, Azure, etc.)
  - Built-in / External
  - Maintainer (ie KEDA, community, ...)
  - Support for (cluster) trigger authentication?

**Comment by chalin** [comment]
Do you consider this done or work-in-progress @tomkerkhove?
Should it be assigned to @thisisobate?

/cc @nate-double-u

**Comment by tomkerkhove** [comment]
No because the filtering capabilities are not there yet.

I'm OK with assigning it to @thisisobate but I'm leaving it up to your team as I don't want to push work on your team so feel free to assign how you want to.

**Comment by tomkerkhove** [comment]
And https://github.com/kedacore/keda-docs/issues/845 & https://github.com/kedacore/keda-docs/issues/857 are also related to this one

**Comment by thisisobate** [comment]
Do we consider this as done? @tomkerkhove 
We've fixed all related issues so I think we should close this one

**Comment by tomkerkhove** [comment]
Not really, we are still missing this
> * Provide filtering on the current overview, examples are:
>   
>   * Categories (ie messaging, databases, CI/CD)
>   * Cloud (Alibaba, AWS, Azure, etc.)
>   * ~Built-in / External~
>   * Maintainer (ie KEDA, community, ...)

**Comment by thisisobate** [comment]
I originally thought the search bar already solves the filtering capabilities but it seems I'm wrong

**Comment by tomkerkhove** [comment]
No, the idea is to have something similar to this:
![image](https://user-images.githubusercontent.com/4345663/190070506-0eaa6c4c-6d3f-4cbe-b7bc-ff426be2beca.png)

**Comment by thisisobate** [comment]
@tomkerkhove I noticed that there are no "category" nor "cloud" label/tag in the scaler's metadata. This affects all the scaler docs for every version.

If you want to list these labels in the filter, then I would advise you open a PR that updates the docs metadata accordingly. For now, I will focus on listing just the "maintainer" label.

**Comment by thisisobate** [comment]
so ideally, what is needed is to add your desired category in the front matter. For example, see how I added `category = "database"` to `cassandra.md`:
```
+++
title = "Cassandra"
availability = "v2.5+"
maintainer = "Community"
description = "Scale applications based on Cassandra query results."
category = "database"
go_file = "cassandra_scaler"
+++

### Trigger Specification

This specification describes the `cassandra` trigger that scales based on the outputs of a Cassandra query.
```

**Comment by tomkerkhove** [comment]
Would these need to be pre-defined for the filtering to work or not?

@kedacore/keda-maintainers I'm fine with this, any objections?

**Comment by zroubalik** [comment]
LGTM

**Comment by tomkerkhove** [comment]
What about you @JorTurFer?

**Comment by JorTurFer** [comment]
I see it as a good improvement!

**Comment by tomkerkhove** [comment]
I have created https://github.com/kedacore/keda-docs/issues/1401 to annotate things

**Comment by tomkerkhove** [comment]
https://github.com/kedacore/keda-docs/pull/1405 was created to add the categories

**Comment by tomkerkhove** [comment]
https://github.com/kedacore/keda-docs/pull/1405 is merged so you should be unblocked @thisisobate

**Comment by tomkerkhove** [comment]
Would you mind documenting in https://github.com/kedacore/keda-docs/blob/main/README.md what it takes to introduce a new category? We'd prefer not to have to bother you for future ones

**Comment by thisisobate** [comment]
What are you referring to as a category? If you mean the `category` filter option, then introducing a new category is fairly automatic; all you need to do is add the new category to the frontmatter and it's shown on the UI by default. So for example, adding "runtime" as a new category like this:
```
+++
title = "Keda Runtime"
availability = "v2.5+"
maintainer = "Community"
description = "Scale applications based on Cassandra query results."
category = "runtime"
go_file = "keda_runtime"
+++

### Specification

This specification describes the .........
```

**Comment by thisisobate** [comment]
Shall we go ahead and close this since it's now completed by #1400? @tomkerkhove

**Comment by tomkerkhove** [comment]
No, let's clarify this first.

I should not have used "category" as a word but let's say filter. As of now, we don't have one to indicate "experimental" vs "stable". If we were to add this, what are the steps to take? Can you please document that in the README?

**Comment by thisisobate** [comment]
ok...that makes sense.
sure, happy to do it

**Comment by tomkerkhove** [comment]
Thank you!
