### ISSUE TITLE
Provide a catalog of tools/products integrating with KEDA

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#413]
Provide a catalog of tools/products integrating with KEDA so that people can understand how they can combine both to build scalable platforms.

The idea is to have a page similar to the scalers that lists all of them with a dedicated page that briefly explains what it does and how it uses KEDA.

Examples are Apache Airflow, Azure Functions, etc.

**Comment by tomkerkhove** [comment]
This is what we've discussed @zroubalik, clear enough or should I add something?

**Comment by zroubalik** [comment]
LGTM!

**Comment by tomkerkhove** [comment]
Adding to https://github.com/orgs/kedacore/projects/5 as we need to have the capability in website before we can add the data

**Comment by tomkerkhove** [comment]
@kedacore/keda-maintainers CNCF team is asking for examples - Mind sharing a few more than Azure Functions and Apache Workflow?

The idea is to have a page similar to the scalers, I believe, that lists all of them with a dedicated page that briefly explains what it does and how it uses KEDA.

**Comment by thisisobate** [comment]
@tomkerkhove Can you point me to the exact location in the docs where Apache Workflow or Azure Functions is described in details?
