### ISSUE TITLE
Improvement: Remove the delete instructions for crds from deploying  KEDA

### ISSUE THREAD

**Issue by Shubham82** [kedacore/keda-docs#426]
When we uninstall keda using helm i.e` helm uninstall -n keda keda`  then it delete crds also. so we don't need to delete it separately.
So it should be removed from the keda2.2.0 [docs](https://keda.sh/docs/2.2/deploy/#uninstall).

helm version: v3.5.4
kedacore/charts: 2.2.1
keda: 2.2.0
ref: https://github.com/kedacore/charts/pull/141

if its right then i will create a PR for it.

**Comment by tomkerkhove** [comment]
Sure thing, thanks for the PR!

**Comment by Shubham82** [comment]
Fixed it here #427
