### ISSUE TITLE
Docs for metrics-api scaler incorrectly label types of settings

### ISSUE THREAD

**Issue by coderanger** [kedacore/keda-docs#433]
### Report

Most of the settings listed under Authentication Parameters are actually trigger metadata instead. The examples do show things correctly (I think) but it's hard to understand if you're trying to write a config yourself.

### Expected Behavior

The docs should match reality.

### Actual Behavior

They do not.

### Steps to Reproduce the Problem

1. Read the docs.
2. Write bad code.

### KEDA Version

2.2.0

**Comment by tomkerkhove** [comment]
Thanks for reporting @coderanger, I've moved it to our docs repo but can you elaborate on it please as I'm not sure I get your concern.

**Comment by coderanger** [comment]
https://keda.sh/docs/2.2/scalers/metrics-api/#authentication-parameters indicates all the following keys are authentication params to be used in TriggerAuthentication objects. However most are not, they are trigger metadata and are defined in the trigger itself.

**Comment by tomkerkhove** [comment]
I don't know the actual implementation, but some scalers allow you to pass this kind of information through trigger authentication as well for better management. If they are not accepted then they need to be removed indeed.

**Comment by zroubalik** [comment]
Can we get anybody who worked on this scaler to fix that?
