### ISSUE TITLE
What are the requirements for the external scaler?

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#46]
What are the requirements for the external scaler? From the docs it's not really clear how to use it and how/what the target endpoint should respond.

Can you elaborate a bit on this @ahmelsayed?

**Comment by YourTechBud** [comment]
Here's a clear example on how to use it: https://keda.sh/docs/2.0/concepts/external-scalers/

All you need to do is:
- Create a ScaledObject with a trigger of type `external-push`. Don't forget to specify a `scalerAddress` which is `host:port` of your gRPC server.
- Create a gRPC server which implements the `externalscaler.proto`. An example is provided in the docs

**Comment by ahmelsayed** [comment]
I think this can be closed, right @tomkerkhove

**Comment by tomkerkhove** [comment]
Yes, I think so, thanks for the docs on this @ahmelsayed!
