### ISSUE TITLE
Docs are difficult to read when browser width is constrained

### ISSUE THREAD

**Issue by robin-wayve** [kedacore/keda-docs#470]
When my browser's width is constrained, the documentation becomes difficult to read because content overflows and is not scrollable.

## Expected Behavior

The style should allow the content column to be scrolled when the content overflows.

## Actual Behavior

The content is clipped and hidden from view with no possibility to scroll horizontally.

![Screenshot from 2021-06-22 13-41-25](https://user-images.githubusercontent.com/70587124/122926628-fa528d00-d35f-11eb-954b-a4330decf487.png)

## Steps to Reproduce the Problem

  1. Open https://keda.sh/docs/2.3/concepts/scaling-jobs/ in a browser
  2. Resize the window to be narrower than the content (eg. 1270 pixels)
  3. Observe clipped content

## Specifications

  - **KEDA Version:** 2.3 (documentation)
  - **Platform & Version:** Ubuntu Linux: Firefox 89 and Chromium 91
  - **Kubernetes Version:** N/A
  - **Scaler(s):** N/A

**Comment by tomkerkhove** [comment]
Makes sense, are you willing to jump in or are you not a frontend dev like me?😅

**Comment by robin-wayve** [comment]
I'm a rusty full-stacker: I would be happy to pitch in with some pointers.

I wasn't able to hack my way out of this one neatly in the inspector. I thought it might be a simple case of slapping a `overflow: scroll` on something but it didn't seem so straightforward. I'm not familiar enough with Bulma to know if it has some built-in solution for responsive columns like this.

**Comment by tomkerkhove** [comment]
No problem Robin, I'll check with CNCF.
