### ISSUE TITLE
Consistent naming of KEDA acronym

### ISSUE THREAD

**Issue by jacksgt** [kedacore/keda-docs#475]
Hey,

I was recently looking up what the KEDA acronym stands for and came across these two conflicting versions:
https://github.com/kedacore/keda-docs/blob/442a89c68f4ef343c6f779e365c8574b1cb7d9ac/data/faq20.toml#L3
https://github.com/kedacore/keda-docs/blob/442a89c68f4ef343c6f779e365c8574b1cb7d9ac/content/docs/2.3/_index.md#L6

So, is it `Kubernetes-based Event Driven Auto-Scaler` or `Kubernetes Event-driven Autoscaler`?
Personally I think the latter is more correct from a hyphenation point of view.

I know this is a really minor nitpick, but it should be easily fixable.

**Comment by tomkerkhove** [comment]
That would e Kubernetes Event-driven Autoscaler, are you open to send a PR?

**Comment by jacksgt** [comment]
Yes, I will do that. Thanks for the clarification!
