### ISSUE TITLE
Document required Kubernetes version

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#49]
We should document required Kubernetes version for new users under deploy as a prerequisite.

**Comment by tomkerkhove** [comment]
@ahmelsayed What version do we need?

**Comment by zroubalik** [comment]
I'd stick to >= 1.13

**Comment by tomkerkhove** [comment]
Apparently it's already documented under FAQ > "What are the prerequisites for using KEDA?" that it requires Kubernetes cluster >= 1.11.10 but we might want to bump it to 1.13

**Comment by zroubalik** [comment]
@tomkerkhove let's bump it to 1.13

**Comment by tomkerkhove** [comment]
I'll pick this up!
