### ISSUE TITLE
Provide new scaler template

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#51]
Provide a template that can be used to document new scalers so that all scalers use a similar doc approach.

The template should come with a brief doc describing what the goal is and what should be documented.

**Comment by tomkerkhove** [comment]
@melmaliacone If you are interested, feel free to have a look at this one and tell me if you find this valuable or not.

**Comment by melmaliacone** [comment]
> @melmaliacone If you are interested, feel free to have a look at this one and tell me if you find this valuable or not.

I think this is a great idea. I was actually thinking yesterday that I wished the scaler documentation was standardized since it varies a lot from scaler to scaler.

**Comment by tomkerkhove** [comment]
Great to hear!

**Comment by tomkerkhove** [comment]
Done via https://github.com/kedacore/keda-docs/pull/124 and is documented on https://github.com/kedacore/keda-docs#adding-scaler-documentation
