### ISSUE TITLE
Azure Blob Storage 2.x do not mention 'accountName'

### ISSUE THREAD

**Issue by joachimgoris** [kedacore/keda-docs#510]
**Report**

The documentation of Azure Blob Storage fail to mention `accountName`. In the source code, we see this is required for all 2.x versions of the trigger when using podIdentity.

## Expected Behavior

The spec and examples in the document mention `accountName` and explain what it does.

## Actual Behavior

`accountName` is entirely missing.

## Steps to Reproduce the Problem

  1. Read the docs
  2. Try to use Azure Blob Storage trigger with podIdentity.
  3. Get confused about errors.

## Specifications

  - **KEDA Version:** 
 All 2.x versions
  - **Platform & Version:** 
 _No response_
  - **Kubernetes Version:** 
 _No response_
  - **Scaler(s):**
 _No response_

**Comment by tomkerkhove** [comment]
Done in #511
