### ISSUE TITLE
[Feature request] Chinese doc support

### ISSUE THREAD

**Issue by yxxhero** [kedacore/keda-docs#532]
### Use-Case
Chinese doc support

**Comment by yxxhero** [comment]
Multi-language support

**Comment by tomkerkhove** [comment]
Unfortunately we don't speak chinese, what would be your recommendation?

**Comment by yxxhero** [comment]
At present, like k8s, it can support multiple languages, put them in different directories, such as en Zh, etc., and then contribute through the strength of the community. @tomkerkhove
