### ISSUE TITLE
Provide overview of all external scalers

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#577]
Provide overview of all external scalers that are available.

This information should be based on Artifact Hub - https://artifacthub.io/packages/search?kind=8&sort=relevance&page=1

Kept is using a similar approach: https://keptn.sh/docs/integrations/

Relates to #412

**Comment by arschles** [comment]
I like this idea @tomkerkhove. Do you think we should write a script to pull from Artifact Hub?

**Comment by tomkerkhove** [comment]
Nope, they allow us to embed everything :) But I'll ask the CNCF to help us to revamp the whole experience with filters based on the categories.

**Comment by chalin** [comment]
Are the cards used to display scalars on the homepage, the kind of card you'd like used on the Scalars page too?

Screenshot from the homepage:

> ![image](https://user-images.githubusercontent.com/4140793/142405483-c0661547-1145-4682-a727-e8713c0173d2.png)

**Comment by tomkerkhove** [comment]
We don't have a strong requirement on the info but would be nice to surface the name, availability and categories that we'd like to introduce.

**Comment by thisisobate** [comment]
@tomkerkhove I'm taking a look at this one.
/assign @thisisobate
