### ISSUE TITLE
List of scalers in navigation does not support scrolling

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#581]
List of scalers in navigation does not support scrolling which makes it impossible to see the scalers at the end of the list.

**Comment by chalin** [comment]
The list is too long, from a design perspective we shouldn't be trying to list them all in a top-nav dropdown menu, nor the left sidenav IMHO.

As you probably have noticed, this is how [keptn.sh](https://keptn.sh/docs/) is setup:

<img width="1010" alt="Screen Shot 2021-11-18 at 6 10 52 AM" src="https://user-images.githubusercontent.com/4140793/142405114-d2075480-8602-4c0b-8a63-155ee4320f1a.png">

Is a similar UI ok with you?

/cc @nate-double-u @celestehorgan

**Comment by tomkerkhove** [comment]
It definately is OK for me as we want to start introducing categories. What do you think @kedacore/keda-maintainers?

**Comment by zroubalik** [comment]
OK for me :)
