### ISSUE TITLE
Website does not render correctly on mobile

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#582]
Website does not render correctly on mobile which makes you swipe to the right to see the navigation which has a white gap.

**Comment by chalin** [comment]
Are there specific issues that you'd like addressed, other than the horizontal scrolling of some of the pages like the homepage:

> <img src="https://user-images.githubusercontent.com/4140793/142298290-9f407726-2300-4068-a881-322a74cabadf.png" width=250>

/cc @nate-double-u

**Comment by tomkerkhove** [comment]
I think that's about right, unless you have other issues @zroubalik ?

**Comment by chalin** [comment]
Related: https://github.com/kedacore/keda-docs/discussions/503

**Comment by zroubalik** [comment]
Yeah, that's the main problem imho, thanks @chalin
