### ISSUE TITLE
Calendar link for Community call is missing

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda-docs#59]
There is a calendar link for Community call on https://github.com/kedacore/keda#community but is missing in the respective section on https://keda.sh

**Comment by tomkerkhove** [comment]
It's still open for review on https://github.com/kedacore/keda-docs/pull/52

**Comment by zroubalik** [comment]
Sorry, haven't noticed

**Comment by tomkerkhove** [comment]
No worries man! Merged.

**Comment by tomkerkhove** [comment]
And thanks for checking!
