### ISSUE TITLE
Improve docs for Azure Pipelines scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda-docs#596]
There are several users who have problem with this scaler and in particular with the `poolID`. 
Doc doesn't explain explicitly how to get the `poolID` apart from the comment in the line that it's not totally visible
`Can be retrieved by the REST API call https://dev.azure.com/{organizationName}/_apis/distributedtask/pools?poolname={agentPoolName}` 
AFAIR, the `poolID` could be get using the REST API but also az-cli.

Depth in this to find all the ways to get the `poolID` and improve the docs would be nice.

**Comment by tomkerkhove** [comment]
Huh, distributedtask, what's the differnce with agentpool?

**Comment by JorTurFer** [comment]
IDK but in my case, if I use agentqueues i get 155
![image](https://user-images.githubusercontent.com/36899226/143399068-360c25bc-422e-4157-9acb-c0cb485547b3.png)
and if I use distributedtask  I get 11 (in fact, 11 is the correct value)
![image](https://user-images.githubusercontent.com/36899226/143399345-880e82cf-d679-432d-b5ed-4402c4659531.png)

**Comment by JorTurFer** [comment]
The scaler creator wrote it in the documentation also 
![image](https://user-images.githubusercontent.com/36899226/143399557-9ed70f33-185a-4a9e-a3e9-51d67b8a22dd.png)

**Comment by tomkerkhove** [comment]
Huh interesting, this might have been a misunderstanding from my side (and maybe others).

Do you know what the difference is?

**Comment by tomkerkhove** [comment]
Let's maybe remove the `1` default as people might thing this will be the value when they create their first pool? Might be overthinking this as well.

**Comment by JorTurFer** [comment]
> Huh interesting, this might have been a misunderstanding from my side (and maybe others).
> 
> Do you know what the difference is?

Not yet, but maybe I will discover it when I'm doing [the changes to throw an error if not exist](https://github.com/kedacore/keda/issues/2342). If I discover any interesting thing I will update this thread

**Comment by tomkerkhove** [comment]
Let's add a dedicated section to put the emphasize on it, something like "Determining the agent pool ID" as an h3 or so - What do you think?
