### ISSUE TITLE
Add version number to doc search results

### ISSUE THREAD

**Issue by chrisreddington** [kedacore/keda-docs#619]
Please add the version number to search results when using the built-in search functionality on keda.sh. Currently, if you search for an item and it appears in older versions, then there may be confusion on which version you're using. I assumed that if there are multiple results, the highest item would be the latest, though this is not the case.

![image](https://user-images.githubusercontent.com/791642/148208393-4838f324-be5b-4672-83d3-e52c2d904a67.png)

### Use-Case

As an example scenario, navigate to keda.sh. In the search box, enter "azure pod identity". This returns several results, all of which look like they point to the same page. It's only when you navigate over the links that you can see they point to different versions of Keda. Thanks to @tomkerkhove on #618 for pointing this out to me, as I hadn't realised.

To avoid this scenario, it would be great if the version of the page could also be added into the search result.

### Specification

- [ ] Add the version of the page into the search result.

**Comment by chalin** [comment]
I think that there might be a way to do this without having to change the display of search results but including the doc version in the title (and removing the labels like "Click here for latest"). /cc @celestehorgan @nate-double-u

**Comment by nate-double-u** [comment]
/reopen
still important

**Comment by thisisobate** [comment]
I took this for a spin and this is what I discovered:

Algolia creates and manages the search index for you which means you can't really change how the data is represented on the search results display. 

The best possible solution is to filter query results using the current version. This should occur before the index is created.

To achieve this, the config has to be modified and from the look of things, there seems to be a new way of managing config details: 

> All of the configs can now be edited directly from [our web interface](https://crawler.algolia.com/) which also offer you a way to start new crawls

Read more [here](https://github.com/algolia/docsearch-configs/tree/master)

@tomkerkhove Do you or any of the maintainers have access to the Keda Algolia account?

**Comment by tomkerkhove** [comment]
Unfortunately not, this was set up by CNCF AFAIK. I recall @nate-double-u was recently trying to recover some accounts
