### ISSUE TITLE
Fix redirect rules and drop misnamed and misplaced _redirects files

### ISSUE THREAD

**Issue by chalin** [kedacore/keda-docs#668]
Redirect rules should be defined in [layouts/index.redirects](https://github.com/kedacore/keda-docs/blob/main/layouts/index.redirects).

The following two files should be deleted. We might need to ensure that their rules are covered first thought:

- [x] Drop https://github.com/kedacore/keda-docs/blob/main/content/_redirects - #670
- [ ] Drop https://github.com/kedacore/keda-docs/blob/main/static/_redirects
- Preserve `/concepts/overview` rule (all other rule are covered by the generated redirects file).
- [ ] Drop unnecessary `301!` rule qualifiers

**Comment by chalin** [comment]
@tomkerkhove - as was mentioned in the opening comment, the following rules aren't being processed by Netlify:

https://github.com/kedacore/keda-docs/blob/edde5ffae2f12d3d93d7d2b01ed59d8c3ca615e9/static/_redirects#L1-L4

Some of these are encoded in the [layouts/index.redirects](https://github.com/kedacore/keda-docs/blob/main/layouts/index.redirects), but not all. Do you need these rules?

Also note that the `deploy` redirect rule is missing a `/`. That is:

- https://keda.sh/deploy, redirects to
- https://keda.sh/docs/2.6deploy (which is a 404)

/cc @nate-double-u

/tag cleanup
/tag bug

**Comment by tomkerkhove** [comment]
Yes, we need those indeed but these should work normally; for example if you go to `https://keda.sh/docs/latest/scalers/` it will go to `https://keda.sh/docs/2.6/scalers/`

But I'm not sure if it's that or because of the versions. If I recall correctly these were there for our old docs, but not a must from my side.

Thoughts @kedacore/keda-maintainers?

**Comment by zroubalik** [comment]
> Yes, we need those indeed but these should work normally; for example if you go to `https://keda.sh/docs/latest/scalers/` it will go to `https://keda.sh/docs/2.6/scalers/`
> 
> But I'm not sure if it's that or because of the versions. If I recall correctly these were there for our old docs, but not a must from my side.
> 
> Thoughts @kedacore/keda-maintainers?

+1

**Comment by chalin** [comment]
> Yes, we need those indeed but these should work normally; for example if you go to `https://keda.sh/docs/latest/scalers/` it will go to `https://keda.sh/docs/2.6/scalers/`

FYI, https://github.com/kedacore/keda-docs/blob/main/static/_redirects get overwritten by the generated file of the same name. All rules have an equivalent in the generated file except for this redirect:

```console
$ curl -s -D - -o /dev/null https://keda.sh/concepts/overview
HTTP/2 404
```

Just to be clear: so you'd like me to add a rule for `concepts/overview`?

**Comment by tomkerkhove** [comment]
I'd say ensure we have rules for all of these:
https://github.com/kedacore/keda-docs/blob/edde5ffae2f12d3d93d7d2b01ed59d8c3ca615e9/static/_redirects#L1-L4

**Comment by tomkerkhove** [comment]
Bump

**Comment by JorTurFer** [comment]
Is this solved?

**Comment by JorTurFer** [comment]
Is this solved?

**Comment by JorTurFer** [comment]
should we mark this as ignored for stale bot?
