### ISSUE TITLE
Change page titles so that page-content title comes before the site title

### ISSUE THREAD

**Issue by chalin** [kedacore/keda-docs#678]
Currently page titles are of the form `KEDA | <content-title>`. It is more typical (and makes analytics analytics easier) if title has a format like `<content-title> | KEDA`.

Any objections to making this change @tomkerkhove et all?

**Comment by tomkerkhove** [comment]
@kedacore/keda-maintainers Any objections on this?

**Comment by zroubalik** [comment]
+1

**Comment by tomkerkhove** [comment]
Majority, let's do it @chalin!
