### ISSUE TITLE
Should we remove /docs from our URLs?

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#679]
Currently our URL looks like `keda.sh/docs/latest/troubleshooting` and I'm wondering if we should keep it or not?

If we change it, though, it should autodirect to avoid breaking things.

**Comment by tomkerkhove** [comment]
Thoughts @kedacore/keda-maintainers @chalin?

**Comment by chalin** [comment]
Having top-level sections like `/docs` and `/blog` is quite standard. The only times I've seen sites without `/docs` is when the entire site is _just_ docs (so essentially the entire content of what is usually under `/docs` gets promoted to the top level).

I suggest keeping `/docs`. (Or have I misunderstood your question?)

**Comment by tomkerkhove** [comment]
Makes sense, I was just wondering why but that explains it.
