### ISSUE TITLE
Solace PubSub+ Event Broker has no "latest" version

### ISSUE THREAD

**Issue by chalin** [kedacore/keda-docs#693]
1. Visit https://keda.sh/docs/2.4/scalers/solace-pub-sub/
 2. Click on [Click here for latest](https://keda.sh/docs/2.6/scalers/solace-pub-sub/)

This results in a 404. I'd either expect the "latest" button to be absent or the target page to exist.

**Comment by tomkerkhove** [comment]
Also, we should make sure it's not absent :D

**Comment by chalin** [comment]
@tomkerkhove: should that page appear in all versions of the docs as of 2.4?

**Comment by chalin** [comment]
For example, consider the [cron scaler](https://keda.sh/docs/1.5/scalers/cron/), which has the following versions of that scaler's page:

```console
$ find content -name "cron.md" | sort
content/docs/1.5/scalers/cron.md
content/docs/2.0/scalers/cron.md
content/docs/2.1/scalers/cron.md
content/docs/2.2/scalers/cron.md
content/docs/2.3/scalers/cron.md
content/docs/2.4/scalers/cron.md
content/docs/2.5/scalers/cron.md
content/docs/2.6/scalers/cron.md
content/docs/2.7/scalers/cron.md
```

It is my understanding that if a scaler appeared in version x.y, then there will be a page for that scaler under all doc versions >= x.y (unless the scaler no longer exists). Is that correct?

If so, then the problem with the Solace pub-sub page is that it hasn't been duplicated since its introduction:

```console
$ find content -name "solace-pub-sub.md" | sort
content/docs/2.4/scalers/solace-pub-sub.md
```

**Comment by tomkerkhove** [comment]
Yes that is correct, ti should be copied to 2.4+

**Comment by chalin** [comment]
Ah, it seems that the files exist, but were renamed:

```console
$ find content -name "**solace*" | sort                                                                            
content/docs/2.4/scalers/solace-pub-sub.md
content/docs/2.5/scalers/solace.md
content/docs/2.6/scalers/solace.md
content/docs/2.7/scalers/solace.md
```

I'll rename them all to `solace-pub-sub.md`, does that work for you @tomkerkhove?

**Comment by zroubalik** [comment]
@chalin yeah, plase do that. Good catch!
