### ISSUE TITLE
Link to specific items in FAQ and Troubleshooting guide

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda-docs#712]
At the moment one can not link to specific items (questions/topics) in FAQ or Troubleshooting guide:
https://keda.sh/docs/2.6/faq/ 
https://keda.sh/docs/2.6/troubleshooting/

Would be nice to add possibility to do that (ie. generate links for each item.

### Use-Case

Access inidividual items in FAQ/Troubleshooting with links

### Specification

- [ ] Generate links for FAQ
- [ ] Generate links for Troubleshooting guide

**Comment by zroubalik** [comment]
@chalin Is this something you can pick up as part of the rework, please?

**Comment by chalin** [comment]
@zroubalik - yes it can be. It would help if I knew the relative priority of issues -- see #727.

**Comment by thisisobate** [comment]
This issue has already been fixed.
PRs: 
- [Feat: copy to clipboard for troubleshooting page](https://github.com/kedacore/keda-docs/pull/1321)
- [Feat: Copy to Clipboard for FAQ](https://github.com/kedacore/keda-docs/pull/1303)

I think we should close this one. 
cc: @tomkerkhove

**Comment by tomkerkhove** [comment]
Yes indeed, thanks!
