### ISSUE TITLE
[meta] Organize and prioritize issues

### ISSUE THREAD

**Issue by chalin** [kedacore/keda-docs#727]
We currently have a growing list of issues in [Documentation Improvements], it would help contributors (including myself :)), to know what to work on next if you would consider doing some/all of the following.

### Relative priority

@tomkerkhove @zroubalik et al., **assign priorities** to the issues by adding one of these labels:

> <img width="300" alt="priorities" src="https://user-images.githubusercontent.com/4140793/159704361-31df87fa-ef5a-451e-8e69-bea1a3de1620.png">

Also consider adding an **effort estimate** if you have a feeling for the expected effort and you feel it is relevant:

> <img width="300" alt="efforts" src="https://user-images.githubusercontent.com/4140793/159704588-43fdb146-2d66-4e2f-be35-86cebdfaf27a.png">

### Milestones

The current [Documentation Improvements] milestone, isn't really a _milestone_, but rather a category IMHO. For other projects, we've found it useful to setup milestones per quarter, such as `22Q1`, `22Q2`, etc. Would that work for you here too? It would complement the use of priorities. WDYT @tomkerkhove et al.?

[Documentation Improvements]: https://github.com/kedacore/keda-docs/milestone/1

**Comment by tomkerkhove** [comment]
Thank you!

**Comment by tomkerkhove** [comment]
Here you go: https://github.com/orgs/kedacore/projects/5/views/1
