### ISSUE TITLE
Move architecture schematic to repo

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#75]
On [KEDA Architecture](https://keda.sh/concepts/overview/#how-keda-works) we have a visual representation of how KEDA works.

It would be good if we could move the original graphic file to the repo to make changes on it.

Do you have this somewhere @jeffhollan?

**Comment by jeffhollan** [comment]
Yeah I think it was a powerpoint. Let me see if I can dig it up

**Comment by jeffhollan** [comment]
[KEDA architecture.pptx](https://github.com/kedacore/keda-docs/files/4136527/KEDA.architecture.pptx)
