### ISSUE TITLE
Scalers section on landing page is broken on smaller screen

### ISSUE THREAD

**Issue by thisisobate** [kedacore/keda-docs#789]
## Expected Behavior
Content should be fully contained on smaller screens
## Actual Behavior
Content overflows its container on smaller screen
<img width="942" alt="Screenshot 2022-06-21 at 16 24 16" src="https://user-images.githubusercontent.com/29557702/174857945-a00438a2-13da-48c9-8872-c05a8d39b6b0.png">

## Steps to Reproduce the Problem

  1. Go to keda.sh
  2. Scroll down to the **scalers** section.
  3. Resize and notice how the content overflow

## Specifications

  - **KEDA Version:** *Please elaborate*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *Please elaborate*
  - **Scaler(s):** *Please elaborate*

**Comment by tomkerkhove** [comment]
Thanks for reporting! We'll get it fixed.

**Comment by tomkerkhove** [comment]
Thanks a ton!
