### ISSUE TITLE
Provide blog post on upcoming KEDA v2.8 release

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#802]
Provide blog post on upcoming KEDA v2.8 release.

@kedacore/keda-maintainers Please list the most significant changes that you think should be in at least

**Comment by tomkerkhove** [comment]
From my side based on https://github.com/kedacore/keda/blob/main/CHANGELOG.md:
- New scalers
- Support for Azure AD Workload Identity as a pod identity provider
- Support for permission segregation when using Azure AD Pod / Workload Identity
- Migrate e2e test to Go & Improve e2e on PR process

**Comment by JorTurFer** [comment]
I'd add:
- Support to `float` target values (where they make sense, each scaler supports or not it)
- (In progress) Activation and Scaling thresholds
