### ISSUE TITLE
Left navbar becomes blocked on docs landing page

### ISSUE THREAD

**Issue by nate-double-u** [kedacore/keda-docs#809]
Left navbar becomes blocked by the header when fully expanded on the /docs landing page. I expect this is a hugo or theme issue.

/cc @chalin @thisisobate 

## Expected Behavior
nav bar should expand downward, and potentially scroll, not expand upward.

## Actual Behavior
(tested on Mac OS)

Firefox
<img width="1392" alt="Screen Shot 2022-07-11 at 4 57 06 PM" src="https://user-images.githubusercontent.com/4453979/178379119-df5d47ff-6c1e-4540-8462-9838b6cb14ee.png">

Safari
<img width="1392" alt="Screen Shot 2022-07-11 at 5 19 03 PM" src="https://user-images.githubusercontent.com/4453979/178380112-783d1143-c29a-4833-a6e4-e11495f8d6df.png">

**Comment by chalin** [comment]
@nate-double-u - I believe that this was resolved by #893. Can you confirm, and if so, close this issue? Thanks.

**Comment by chalin** [comment]
I'm going to close this since, as I mentioned earlier, I believe that the issue was resolved by #893. @nate-double-u - feel free to reopen the issue if you find it is still present.
