### ISSUE TITLE
Reduce network impact for scaler search

### ISSUE THREAD

**Issue by thisisobate** [kedacore/keda-docs#839]
Currently, the lunr.js package that enables the scaler search is being served via a CDN. As much as this is fast enough, it would be nice to vendorize it to minimize network impact. By so doing, we save some bandwidth for visitors.

**Comment by chalin** [comment]
Can we see some numbers here. I'd vote to keep serving via CDN, but I'm willing to be convinced that this is optimization is worthwhile. Maybe we can discuss this at our next sync? /cc @nate-double-u

**Comment by thisisobate** [comment]
sure...let's discuss during our next sync

**Comment by tomkerkhove** [comment]
I agree with @chalin, let's not overengineer it if we don't need it

**Comment by thisisobate** [comment]
Alright. Will go ahead and close this one to avoid overengineering.
Thanks for sharing your thoughts! @chalin @tomkerkhove
