### ISSUE TITLE
Provide new "Support" page around support in KEDA OSS & vendors providing KEDA with support

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#855]
Provide new "Support" page that gives an overview around support to our end-users:
- What support does KEDA OSS provide (basically https://github.com/kedacore/governance/blob/main/SUPPORT.md)
- Provide an overview of all vendors that provide KEDA as part of their offering/product and provide support for it

The goal is to help end-users make decision on how to use KEDA that fits their needs.

The model should be very easy (similar to end-users) where partners can send a simple PR that gives information around:
- Name of offering
- Name of vendor
- Link to more information

This should be under a new section in the navigation called "Support".

**Comment by tomkerkhove** [comment]
Examples of this are [AKS's add-on](https://docs.microsoft.com/en-us/azure/aks/keda-about) and RedHat who will have this as well (@zroubalik can provide more details).

@kedacore/keda-maintainers Any suggests on how this page should be called?

**Comment by JorTurFer** [comment]
Support is good enough to me 😄

**Comment by tomkerkhove** [comment]
Custom Metrics Autoscaler on OpenShift is another one https://cloud.redhat.com/blog/custom-metrics-autoscaler-on-openshift

**Comment by tomkerkhove** [comment]
Reopening as docs for adding are not there.
