### ISSUE TITLE
Scaler search is not returning results correctly

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#857]
The search on scaler page does not show results when using "Azure"/"AWS"/"Redis" after #805

## Expected Behavior

Show "Azure Service Bus" and others when searching for "Azure"; for example.

## Actual Behavior

No results were found

## Steps to Reproduce the Problem

  1. Search for "Azure", "AWS" or ""Redis" on the scaler page

**Comment by chalin** [comment]
@thisisobate - I think that the "wild card" feature should be dropped. It seems unconventional for a search. Implicitly, when a user types "abc" the search should be for any match _containing_ "abc".

Do you agree @tomkerkhove?

**Comment by tomkerkhove** [comment]
Agreed!

**Comment by chalin** [comment]
Please assign to @thisisobate.

**Comment by thisisobate** [comment]
@chalin You're right. Implicitly, when a user types "abc" the search should be for any match _containing_ "abc". The tricky thing is that for Lunr, it can only match a **word** (term) not **characters**.

E.g, we want to search for scalers that are maintained by Microsoft. We start by entering the "m" character, then "i".
We expect the tool to be smart enough to depict that we mean Microsoft but in reality, it doesn't. This is where the wildcard search comes in.

If we should drop the wildcard search, then it means the user can only receieve results that match **exactly** with the search query. What this means is the search query must match **at least one word** in the index/record/database. Inotherwords, If I search for "Microsoft", it should return every record that contains Microsoft and nothing else.

@tomkerkhove

**Comment by chalin** [comment]
> The tricky thing is that for Lunr, it can only match a **word** (term) not **characters**.

IMHO, then either we shouldn't be using Lunr, or we need to make the necessary adjustments so that we can search for an arbitrary string being contained in the search targets.

**Comment by thisisobate** [comment]
> we need to make the necessary adjustments so that we can search for an arbitrary string being contained in the search targets

Sure...that's what I tried doing with the wildcard thing. Anyways, I've started working on this issue so @tomkerkhove feel free to assign this issue to me

**Comment by thisisobate** [comment]
That could work...would try it this approach and see if it satisfies all the edge cases.
Thanks for the suggestion!

**Comment by thisisobate** [comment]
`*abc ... def*` didn't work for me. I figured I needed to improve the search logic to support both word and character matching. Would push something right away.
