### ISSUE TITLE
Provide support for searching in external scalers

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda-docs#858]
Using the search bar when on the external scalers tab does not filter results.

## Expected Behavior

Show only CosmosDB scaler when typing "Cosmos" in the search bar when on the external scalers tab.

## Actual Behavior

All external scalers are shown.

## Steps to Reproduce the Problem

  1. Visit the scalers page.
  2. Open the external scalers tab.
  3. Type in a search query.

**Comment by tomkerkhove** [comment]
I think that based on this issue and https://github.com/kedacore/keda-docs/issues/845 it's best to start using the Artifact Hub API @thisisobate

**Comment by thisisobate** [comment]
I think this should be considered a feature request instead since the search bar only works for in-built scalers.

**Comment by tomkerkhove** [comment]
I agree on that, but in that case the search should only be visible when you are looking at built-in scalers to improve UX
