### ISSUE TITLE
List all built-in scalers in side-navigation bar

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#860]
List all built-in scalers in side-navigation bar for simplified navigation:

![image](https://user-images.githubusercontent.com/4345663/182547195-a013684d-396d-42e5-b50d-8a8793ffeac5.png)

**Comment by chalin** [comment]
As mention in https://github.com/kedacore/keda-docs/issues/581#issuecomment-972769847, the scalers list was too long and hence was removed. From a UX point of view (both on desktop and mobile) it makes more sense (IMHO) to direct the user to the **Scalers** page where they can use the search with filter etc. Thoughts?

**Comment by tomkerkhove** [comment]
That's nice, however, if I want to go from scaler A to scaler B that takes a lot of clicks.

That's why I'd like to have the list back to simplify it.

**Comment by tomkerkhove** [comment]
This is how I do it on my other OSS project and find super useful -  https://docs.promitor.io/v2.7/scraping/providers/app-plan/

Less clicking to go from one provider to another.

Thoughts @kedacore/keda-maintainers?

**Comment by chalin** [comment]
Ok, I'll have another look.
