### ISSUE TITLE
Confusing (wrong) description on supported replica of metrics server deployment

### ISSUE THREAD

**Issue by zqzten** [kedacore/keda-docs#861]
In [High Availability section of the operate doc](https://keda.sh/docs/2.7/operate/cluster/#high-availability), it said that KEDA metrics server does not support HA according to [limitation in k8s custom metrics server](https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/70).

However, the limitation mentioned is that k8s does not support **more than one type** of custom metrics server but **not more than one replica** of the same custom metrics server. So actually there's no limitation on the replica of KEDA metrics server and it does support HA. Seems the current doc is wrong there.

**Comment by zqzten** [comment]
But the KEDA metrics server is an aggregated apiserver (which naturally support HA) right? Say I have two replicas of it, and there's one down, the other one can still handle the request from HPA controller. I haven't look through the code so I'm not sure if I missed sth.

**Comment by tomkerkhove** [comment]
Yes but it's not going to actively load balance across multiple instances

**Comment by tomkerkhove** [comment]
But @zroubalik might correct me, but I'm pretty sure that's correct

**Comment by zroubalik** [comment]
Yeah, that the usual default way it works, ie. only one instance handles the load. For the requests to be balanced between all the instances of the metrics-apiserver, you need to set `--enable-aggregator-routing=true` on the kube-apiserver.

**Comment by zroubalik** [comment]
The issue is, that once we introduce metrics values caching on the metric server side, then we will have to somehow deal with sharing the cache between multiple replicas

**Comment by zqzten** [comment]
> The issue is, that once we introduce metrics values caching on the metric server side, then we will have to somehow deal with sharing the cache between multiple replicas

Yeah that might be a problem. So the question can become: if I setup KEDA metrics server with HA (more than 1 replica), what possible issue would I meet?

**Comment by tomkerkhove** [comment]
That the only "HA" that you get, is that it will reduce failing over ones the primary fails

**Comment by zroubalik** [comment]
@zqzten no issues at the moment when specifying multiple replicas.

**Comment by zqzten** [comment]
Thanks! So shall we correct the doc to say that KEDA metrics server does support HA with multiple relicas?

**Comment by zroubalik** [comment]
Yeah, that would be great. But we should be careful with the wording, so people don't have the impression that they could have mutliple installations per cluster.

**Comment by tomkerkhove** [comment]
I would prefer not to change it given it's not really HA IMO but if everything things it's best then that's that.

What about this?

> While you can run more replicas of our metric server, only one instance will used and serve traffic.
> 
You can run multiple replicas, but they will not improve the performance of KEDA, it could only reduce downtime during a failover.

**Comment by zqzten** [comment]
> While you can run more replicas of our metric server, only one instance will used and serve traffic.
> 
> You can run multiple replicas, but they will not improve the performance of KEDA, it could only reduce downtime during a failover.

That might not be accurate enough? According to what @zroubalik mentioned, we can achive load balanced HA of KEDA metrics server by setting` --enable-aggregator-routing=true` on the kube-apiserver.

**Comment by zqzten** [comment]
Just found that the official metrics server also has this recommandation, FYI: https://github.com/kubernetes-sigs/metrics-server#high-availability

**Comment by zroubalik** [comment]
Yeah, we can also mention this property there. Are you willing to open a PR to fix this?

**Comment by zqzten** [comment]
> Yeah, we can also mention this property there. Are you willing to open a PR to fix this?

Glad to. I'll open one in these days.
