### ISSUE TITLE
Consider not listing scalers at the end of each individual scaler page

### ISSUE THREAD

**Issue by chalin** [kedacore/keda-docs#869]
Each individual scaler page should be about the scaler itself and nothing else. Why list all scalers at the end of the page? This adds content irrelevant to the scaler which shows up in, e.g., the printed version of the page.

**Comment by chalin** [comment]
@tomkerkhove - any comments about this?

Related:

- #870

**Comment by tomkerkhove** [comment]
I'd say this simplifies navigation but if they are listed in the side navigation as per https://github.com/kedacore/keda-docs/issues/860 then I'm ok with removing them

**Comment by tomkerkhove** [comment]
PS: Add all of these issues to "Documentation Improvements" please :)

**Comment by chalin** [comment]
> I'd say this simplifies navigation but if they are listed in the side navigation as per #860 then I'm ok with removing them

A user can click on **Scalers** in the top-nav (or the nav under mobile) to view all scalers. (I'd vote against #860, as I commented there, since the list of scalers is too long for a nav.)

**Comment by tomkerkhove** [comment]
Too many clicks :) I should go straight from scaler A to B imo.
