### ISSUE TITLE
Don't list all scalers under the concepts page

### ISSUE THREAD

**Issue by chalin** [kedacore/keda-docs#870]
For example, see [Event sources and scalers](http://localhost:8888/docs/2.7/concepts/#event-sources-and-scalers):

> <img width="962" alt="image" src="https://user-images.githubusercontent.com/4140793/182852610-575f434e-f15d-45bc-bc12-051c2f3e2572.png">

Rather than listing all the scalers, it would offer a better UX to direct the reader to the Scalers page, where they can use the search, etc.

Thoughts @tomkerkhove?

**Comment by tomkerkhove** [comment]
I am personally a fan of listing them there and would like to add a section on auth providers as well.

Thoughts @zroubalik @JorTurFer ?

**Comment by zroubalik** [comment]
I like it there as well, but I am not opposed if you prefer to change this.

**Comment by chalin** [comment]
IMHO, it would provide a better **user experience** (UX) to direct the reader to the **Scalars** page where they can see the "whole story" about scalers (both _built-in_ and _external_), and use the filters to search.

Otherwise, we run into issues like these (from a UX perspective):

- The compact list doesn't show external scalers. Is that an issue?
- On mobile, the list is getting a bit long to scroll by, and this will only worsen over time as more scalers are added.

Neither of these points are critical, I'm just sharing with you my (admittedly subjective) opinion with regards to usability. Note that #869 is related to this issue.

If you end up wanting to keep the list, please close the issue. Thanks.

**Comment by JorTurFer** [comment]
I prefer to have all the info in one place and links from everywhere. For me, having the scalers listed everywhere is not necessary, but as you prefer, I don't have any strong opinion about it

**Comment by zroubalik** [comment]
Yeah that sounds reasonable. So it's up to you @tomkerkhove
