### ISSUE TITLE
Docs use incorrect casing for Azure KeyVault `vaultUri`

### ISSUE THREAD

**Issue by pinkfloydx33** [kedacore/keda-docs#877]
The documentation for 2.7 and 2.8 uses the wrong casing for the `azureKeyVault.vaultUri` parameter of `TriggerAuthentication`/`ClusterTriggerAuthentication`. 

The docs indicate it's `vaultURI` which is incorrect and does not validate during deployment. It should be `vaultUri`.
- https://github.com/kedacore/keda-docs/blob/4a9fc49d05496d033011cb0a4d21b136a0048a12/content/docs/2.7/concepts/authentication.md#L118
- https://github.com/kedacore/keda-docs/blob/4a9fc49d05496d033011cb0a4d21b136a0048a12/content/docs/2.7/concepts/authentication.md#L245
- https://github.com/kedacore/keda-docs/blob/4a9fc49d05496d033011cb0a4d21b136a0048a12/content/docs/2.8/concepts/authentication.md#L119
- https://github.com/kedacore/keda-docs/blob/4a9fc49d05496d033011cb0a4d21b136a0048a12/content/docs/2.8/concepts/authentication.md#L247

Interestingly, `vaultURI` *is* the name/casing of the value used in code, but [as you can see](https://github.com/kedacore/keda/blob/b4299cc5a1fb94a19b58145289a40c0198c1a37d/apis/keda/v1alpha1/triggerauthentication_types.go#L185-L186) it's JSON tag uses `vaultUri`

The CRDs also (obviously) use `vaultUri`:
- [TriggerAuthentication](https://github.com/kedacore/keda/blob/6609084eb3e9a2a20df7f995bf43a0391d764ad2/config/crd/bases/keda.sh_triggerauthentications.yaml#L114-L118)
- [ClusterTriggerAuthentication](https://github.com/kedacore/keda/blob/6609084eb3e9a2a20df7f995bf43a0391d764ad2/config/crd/bases/keda.sh_clustertriggerauthentications.yaml#L115-L119)

**Comment by tomkerkhove** [comment]
Would you be open to send a PR to update the 2.7 & 2.8 docs please?

**Comment by v-shenoy** [comment]
This was just me being dumb. 🤦🏽
