### ISSUE TITLE
Version drop-down does not work on auth provider page

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#896]
Version drop-down does not work on auth provider page and redirects to general docs instead of the same provider

Relates to #711

## Expected Behavior

Show different version and redirect to same page.

## Actual Behavior

Shows correct version, but doc root instead.

## Steps to Reproduce the Problem

  1. Go to auth provider page
  2. Select new version in drop-down

Relates to #711

**Comment by v-shenoy** [comment]
This is the case for all pages. It always re-directs to the root page of the selected version.

**Comment by PixelRobots** [comment]
This issue seems to be resolved. 
When changing the drop down to 2.0 it shows 6 providers. When drop down is 2.11 it shows 9 providers.
I suggest we can close this issue now.

**Comment by zroubalik** [comment]
Thanks for checking
