### ISSUE TITLE
Provide docs on using KEDA with HTTP scaling

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#9]
Provide docs on using KEDA with HTTP scaling via Osiris.

Current docs we had on `kedacore/keda`:
> **HTTP scaling integration**
> KEDA enables scaling based on event sources where the event resides somewhere to be pulled. For events like HTTP where the event is pushed to the container, KEDA works side by side with HTTP scale-to-zero components like Osiris or Knative serving. By pairing KEDA with an HTTP scale-to-zero component you can provide rich event scaling for both HTTP and non-HTTP.

**Comment by tomkerkhove** [comment]
I haven't tried this before so:
- Do we have a sample for this?
- What docs should we add?
- How do KEDA and Osiris work together or is this purely Osiris?

Do you know @jeffhollan?

**Comment by jeffhollan** [comment]
> * Do we have a sample for this?

No. Not existing

> * What docs should we add?

I’m not sure we add much. If we did add something it would be in like the FAQ I think about “can KEDA scale HTTP requests”

> * How do KEDA and Osiris work together or is this purely Osiris?

Purely Osiris.  Osiris does 0-1 scaling for HTTP (as well as other alternatives like Knative or OpenFaaS).  If you wanted to do HTTP scaling 1->n based on request rate you *could* use KEDA, but I think what we’d recommend is something like the frontend or ingress or something is emitting metrics to prometheus.  KEDA then scales the deployment using the Prometheus scaler on some rps metric

**Comment by tomkerkhove** [comment]
Interesting, let me put it otherwise - If Azure Function customers move to Kubernetes and they use HTTP trigger; what would be your guidance then?

This feels like a gap in the guidance/docs imo 🤔

**Comment by jeffhollan** [comment]
My guidance to them would be for now they'd have to rely on Kubernetes standard HPA scaling unless they are using an ingress controller that supports RPS scaling.

But would be on this doc https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda

Which I plan to update today with latest KEDA info. I can include a blurb about this

**Comment by tomkerkhove** [comment]
It's documented in FAQ, so closing for now.
