### ISSUE TITLE
Select new Netlify build image

### ISSUE THREAD

**Issue by chalin** [kedacore/keda-docs#904]
As reported via deploy logs:

> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
> All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
> 
> To avoid service disruption, please select a newer build image at the following link:
> https://app.netlify.com/sites/grpc-io/settings/deploys#build-image-selection
> 
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by tomkerkhove** [comment]
Which one do you want?

**Comment by chalin** [comment]
The new default.

**Comment by tomkerkhove** [comment]
Changed and running deployment: https://app.netlify.com/sites/keda/deploys/63038dabd3b18d06a66d3c04
