### ISSUE TITLE
The scaler's close method has already been called once in ScalersCache. PushScaler will call the scaler's close method again.

### ISSUE THREAD

**Issue by WindNotStop** [kedacore/keda-docs#915]
The scaler's close method has already been called once in ScalersCache. PushScaler here will call the scaler's close method again.

## Expected Behavior
The scaler's close method is expected to be called once.

## Actual Behavior
The scaler's close method is actually called twice.

## Steps to Reproduce the Problem

  1. Delete the PushScaler resource.

## Specifications

  - **KEDA Version:** *v2.8*

**Comment by tomkerkhove** [comment]
Not a docs bug, PR is open in https://github.com/kedacore/keda/pull/3599
