### ISSUE TITLE
Metadata and TriggerAuthentication are NOT interchangeable

### ISSUE THREAD

**Issue by BitProcessor** [kedacore/keda-docs#919]
As a new Keda user, I tried to setup the Kafka scaler and ran into the following documentation regarding authentication:
https://keda.sh/docs/2.8/concepts/authentication/#re-use-credentials-and-delegate-auth-with-triggerauthentication

On this page, it mentions both:
```
Every parameter you define in TriggerAuthentication definition does not need to be included in the metadata of the trigger for your ScaledObject definition. To reference a TriggerAuthentication from a ScaledObject you add the authenticationRef to the trigger.
```
and
```
Some metadata parameters will not allow resolving from a literal value, and will instead require a reference to a secret, config map, or environment variable defined on the target container.
```

The first one of the above seems to suggest that metadata and TriggerAuthentication entries are interchangeable.
The latter tells the opposite.

This is rather confusing.

**Comment by tomkerkhove** [comment]
> Every parameter you define in TriggerAuthentication definition does not need to be included in the metadata of the trigger for your ScaledObject definition. To reference a TriggerAuthentication from a ScaledObject you add the authenticationRef to the trigger.

This says that some of the things for the metadata can be configured through `TriggerAuthentication` but it does not mention that everything can be configured that way.

That's why we have the "Authentication Parameters" section for every scaler: https://keda.sh/docs/2.8/scalers/activemq/#authentication-parameters

If it would help, we could add an entry there saying everything listed in this section can be configured n `TriggerAuthentication` with the mentioned parameter names?

**Comment by BitProcessor** [comment]
@tomkerkhove I think you are confirming what I am saying: 

> This says that some of the things for the metadata can be configured through TriggerAuthentication but it does not mention that everything can be configured that way.

You are also writing "**_can be configured_**"
The point I am trying to make, is that some items **have to be** in the `TriggerAuthentication` and do not work when they are in the metadata as plain strings. Which is what I believe the second doc entry tells:

> Some metadata parameters will not allow resolving from a literal value, and will instead require a reference to a secret, config map, or environment variable defined on the target container.

More concrete, I ran into this when configuring the Kafka scaler, see this conversation:
https://kubernetes.slack.com/archives/CKZJ36A5D/p1661857098145309?thread_ts=1661773264.659599&cid=CKZJ36A5D

What would have helped, in my case, was something that tells: `username`, `tls` and `sasl` are required to be configured as `TriggerAuthentication` and referenced by `authenticationRef` and will not work when put in the metadata section.
