### ISSUE TITLE
Provide versioning for our FAQ

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#935]
Provide versioning for our FAQ, given the FAQ data is specific per version (ie supported Kubernetes version)

https://keda.sh/docs/2.9/faq/

**Comment by thisisobate** [comment]
@tomkerkhove I think this is already completed I guess?

**Comment by tomkerkhove** [comment]
Not really, there is an FAQ file per version but it all pulls from https://github.com/kedacore/keda-docs/blob/main/data/faq20.toml which is shared across all versions

**Comment by thisisobate** [comment]
Then I guess we just have to update 2.14 and above to not pull from `faq20.toml`.

**Comment by thisisobate** [comment]
Will have to keep this one pending until #1389 gets merged.
