### ISSUE TITLE
Update FAQ for v2.9 to emphasize Kubernetes v1.23+ is required

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#936]
Update FAQ for v2.9 to emphasize Kubernetes v1.23+ is required

Depends on https://github.com/kedacore/keda-docs/issues/935

**Comment by tomkerkhove** [comment]
Already documented on https://keda.sh/docs/2.9/operate/cluster/#kubernetes

**Comment by JorTurFer** [comment]
If it's already documented, shall we close this?

**Comment by tomkerkhove** [comment]
Let's!

**Comment by tomkerkhove** [comment]
Actually this is for the FAQ so I'm re-opening this
