### ISSUE TITLE
Please extend documentation on external metrics api being unavailable 

### ISSUE THREAD

**Issue by hajdukd** [kedacore/keda-docs#986]
Update docs with more examples of what can cause the issue.

### Use-Case

I'm currently facing a situation where keda-metrics-server is not available due to "Address is not allowed"
Firewall seems to allow communication between api-server and pod on port 6443, covered the docs and dis does not help 👍 
Looking for other guesses what can be wrong ;) 

### Specification

- Please extend https://github.com/kedacore/keda-docs/blob/main/content/troubleshooting/keda-external-metrics-issue.md, with possible investigation - for Cillium or other CNI / AWS

**Comment by tomkerkhove** [comment]
We'd love to, but in order to do that we need to have cases that we should document :)

So we're actually looking forward to hearing what your issue was so we can add it to the docs.

It sounds like it is related to permissions/networking though.
