### ISSUE TITLE
Connection string authentication is not documented for Azure Event Hubs

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#993]
Connection string authentication is not documented for Azure Event Hubs when using trigger authentication.

https://keda.sh/docs/2.8/scalers/azure-event-hub/

**Comment by tomkerkhove** [comment]
@v-shenoy As far as I know, end-users can use `connection` and `storageConnection` as parameter names for TriggerAuthentication - Is that correct?

**Comment by v-shenoy** [comment]
> @v-shenoy As far as I know, end-users can use `connection` and `storageConnection` as parameter names for TriggerAuthentication - Is that correct?

Yup.

**Comment by tomkerkhove** [comment]
Thanks for confirming!
